### ISSUE TITLE
Sort splits in descending order

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#10]
Usually we want to retain the longest known word e.g.
asti+uttarasyAm+diSi
is much better than
asti+ut+tara+syAm+diSi.

A rough idea would be to arrange in descending order of length of flattened list.

This will ensure that more probable splits show up in ranking.

**Comment by avinashvarna** [comment]
I am not sure it is always better in all cases. E.g. given varadeva
vara + deva
varadaa + iva
varade + ava
(and the numerous other splits that the splitter returns), it is difficult to say which one is better in a given context. I feel that it is better to leave it up to some higher layer / calling function to figure out what to do with the splits.

**Comment by kmadathil** [comment]
Probably not better in all cases, but doesn't hurt presentation. Added in commit f2623ba

$ python SanskritLexicalAnalyzer.py astyuttarasyAMdishi --split
Parsing of XMLs started at 2017-07-06 13:54:26.062049
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-06 13:54:30.985066
Input String: astyuttarasyAMdishi
Input String in SLP1: astyuttarasyAMdiSi
Start split: 2017-07-06 13:54:32.995393
End split: 2017-07-06 13:54:32.995905
[[u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttaras', u'yAm', u'diSi'], [u'asti', u'uttara', u'syAm', u'diSi'], [u'asti', u'uttas', u'asyAm', u'diSi'], [u'asti', u'ut', u'taras', u'yAm', u'diSi'], [u'asti', u'ut', u'tara', u'syAm', u'diSi']]
