### ISSUE TITLE
ninAdavaDDamarvayam split

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#100]
vat does not figure in any of the splits. Only vaT figures.

{"input":"ninAdavaDDamarvayam","devanagari":"निनादवड्डमर्वयम्","splits":[["नि","नाद","वट्","डमरु","अयम्"],["नि","नाद","वट्","डमरू","अयम्"],["नि","न","आद","वट्","डमरु","अयम्"],["नि","न","अत्","अवट्","डमरु","अयम्"],["नि","न","आद","वट्","डमरू","अयम्"],["नि","न","अत्","अवट्","डमरू","अयम्"]]}

**Comment by kmadathil** [comment]
@avinashvarna 
Do we handle जश्त्वम् followed by ष्टुत्वम ?‌
