### ISSUE TITLE
jaTATavIgalajjalapravAhapAvitasthale issues

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#102]
1. Weightage of jaTA should have some precedence over jaTa. jaTa may be a dictionary word, but not so frequent in corpus as jaTA.
2. pAvita to pau ita is theoretically correct, but we should also see pAvita as a whole word.

{"input":"jaTATavIgalajjalapravAhapAvitasthale","devanagari":"जटाटवीगलज्जलप्रवाहपावितस्थले","splits":[["जट","अटवी","गलत्","जल","प्रवाह","पौ","इत","स्थले"],["जटा","अटवी","गलत्","जल","प्रवाह","पौ","इत","स्थले"],["जट","अटवी","गलत्","जल","प्र","वाह","पौ","इत","स्थले"],["जटा","अटवी","गलत्","जल","प्र","वाह","पौ","इत","स्थले"],["जट","अटवी","गलत्","जल","प्र","वाः","ह","पौ","इत","स्थले"],["जटा","अटवी","गलत्","जल","प्र","वाः","ह","पौ","इत","स्थले"],["जट","अटवी","गलत्","जल","प्र","वा","आह","पौ","इत","स्थले"],["जटा","अटवी","गलत्","जल","प्र","वा","आह","पौ","इत","स्थले"],["जट","अटवी","गलत्","जल","प्र","वा","ह","पौ","इत","स्थले"],["जटा","अटवी","गलत्","जल","प्र","वा","ह","पौ","इत","स्थले"]]}

**Comment by kmadathil** [comment]
@drdhaval2785 - split mode currently produces all splits. We have not added any corpus weighting, but that can be considered. 
Not sure why pAvita is not in the forms dictionary. @avinashvarna ?

**Comment by avinashvarna** [comment]
Related to #104 as well, since the online API was using just the INRIA dataset which does not have pAvita. MW does, and so works slightly better now:
{  "input": "jaTATavIgalajjalapravAhapAvitasthale",
  "devanagari": "जटाटवीगलज्जलप्रवाहपावितस्थले",
  "splits": [ [   "जटा",   "आटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जट",   "अटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जटा",   "अटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जट",   "आटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जटा",   "आटवी",   "ई",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जटा",   "आटवी",   "गलत्",   "जल",   "प्रवाह",   "पावित",   "स्थले" ], [   "जटा",   "आटवी",   "गलत्",   "जलप्रवाह",   "प",   "आवित",   "स्थले" ], [   "जटा",   "आटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थ",   "ले" ], [   "ज",   "ट",   "अटवी",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ], [   "जट",   "अटवी",   "ई",   "गलत्",   "जलप्रवाह",   "पावित",   "स्थले" ]  ]}

It would be interesting to run this on the scoring branch and see if the score for the split with jaTA is better. Unfortunately, I am on a windows machine right now and can't run sentencepiece.

**Comment by kmadathil** [comment]
(scoring)*$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split  "jaTATavIgalajjalapravAhapAvitasthale" --strict
Interpreting input strictly
Input String: jaTATavIgalajjalapravAhapAvitasthale
Input String in SLP1: jawAwavIgalajjalapravAhapAvitasTale
Start Split
End DAG generation
End pathfinding 1545084410.7959135
Splits:
[jawa, awavI, galat, jalapravAha, pAvita, sTale]
[jawA, awavI, galat, jalapravAha, pAvita, sTale]
[jawa, AwavI, galat, jalapravAha, pAvita, sTale]
[jawA, AwavI, galat, jalapravAha, pAvita, sTale]
[jawa, awavI, I, galat, jalapravAha, pAvita, sTale]
[jawa, awavI, galat, jala, pravAha, pAvita, sTale]
[jawa, awavI, galat, jalapravAha, pA, avita, sTale]
[jawa, awavI, galat, jalapravAha, pAvita, sTa, le]
[ja, wa, AwavI, galat, jalapravAha, pAvita, sTale]
[jawA, awavI, I, galat, jalapravAha, pAvita, sTale]
-----------
Performance
Time for graph generation = 0.881842s
Total time for graph generation + find paths = 0.886024s

**Comment by avinashvarna** [comment]
@kmadathil, Need to provide the --score option to activate the scoring feature.

**Comment by avinashvarna** [comment]
On scoring branch, the desired split is ranked highest. Maybe we should invest some time to make the scoring branch cross-platform. I will try to work on it as time permits.

```
python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split  "jaTATavIgalajjalapravAhapAvitasthale" --strict --score
Interpreting input strictly
Input String: jaTATavIgalajjalapravAhapAvitasthale
Input String in SLP1: jawAwavIgalajjalapravAhapAvitasTale
Start Split
End DAG generation
End pathfinding
Splits:
([jawA, awavI, galat, jala, pravAha, pAvita, sTale], -106.310036)
([jawA, awavI, galat, jalapravAha, pAvita, sTale], -108.03929)
([jawa, awavI, galat, jalapravAha, pAvita, sTale], -109.66657)
([jawa, AwavI, galat, jalapravAha, pAvita, sTale], -111.90667)
([jawA, awavI, galat, jalapravAha, pAvita, sTa, le], -112.00773)
([jawA, awavI, galat, jalapravAha, pa, Avita, sTale], -112.95534)
([jawA, AwavI, galat, jalapravAha, pAvita, sTale], -117.7737)
([ja, wA, AwavI, galat, jalapravAha, pAvita, sTale], -121.8567)
([jawA, awavI, i, galat, jalapravAha, pAvita, sTale], -121.96773)
([jawa, AwavI, i, galat, jalapravAha, pAvita, sTale], -125.263725)
```

**Comment by avinashvarna** [comment]
I take that back. Apparently, there is now a python module that seems to work on my Windows machine (I don't recall seeing it when I originally implemented the scoring portion). So it should already by cross-platform if we supply the appropriate python dependencies (sentencepiece and gensim)

**Comment by drdhaval2785** [comment]
Time to integrate @avinashvarna and @kmadathil?

**Comment by kmadathil** [comment]
Since there's an option that can be turned on/off there should not be any objections to merging to master, as long as we can verify that it works cross-platform. 
@avinashvarna - can you create a PR or merge if you're ok?

**Comment by avinashvarna** [comment]
Will do it in the weekend.

**Comment by kmadathil** [comment]
(py36) karthick@karthick-ThinkPad-E450:~/personal_projects/sanskrit/sanskrit_parser (master)$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split  "jaTATavIgalajjalapravAhapAvitasthale" --strict 
Interpreting input strictly
Input String: jaTATavIgalajjalapravAhapAvitasthale
Input String in SLP1: jawAwavIgalajjalapravAhapAvitasTale
Start Split
End DAG generation
End pathfinding 1548555256.539953
Splits:
[jawA, awavI, galat, jala, pravAha, pAvita, sTale]
[jawA, awavI, galat, jalapravAha, pO, ita, sTale]
[jawA, awavI, galat, jala, pravAha, pO, ita, sTale]
[jawA, awavI, galat, jalapravAha, pAvita, sTale]
[jawa, awavI, galat, jala, pravAha, pAvita, sTale]
[jawa, awavI, galat, jalapravAha, pO, ita, sTale]
[jawA, awavI, galat, jalapravAha, pa, avita, sTale]
[jawa, awavI, galat, jala, pravAha, pO, ita, sTale]
[jawa, awavI, galat, jalapravAha, pAvita, sTale]
[jawA, awa, vI, galat, jala, pravAha, pO, ita, sTale]
-----------
Performance
Time for graph generation = 0.923462s
Total time for graph generation + find paths = 0.980681s

@drdhaval2785  - can we close this?

**Comment by avinashvarna** [comment]
Updated on API server as well
https://api.vedavaapi.org/py_skt_parser/sanskrit_parser/v1/splits/jaTATavIgalajjalapravAhapAvitasthale

**Comment by kmadathil** [comment]
Done
