### ISSUE TITLE
anusvAras not handled in split

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#103]
BujaMgatuMgamAlikAm does not yield any results,
While BujaNgatuNgamAlikAm does yield results.

We can not be too sure what convention the user will use. We should convert anusvAra to varga panchama letter if need be from our side.

**Comment by kmadathil** [comment]
Strictly speaking, भुजङ्ग is the only correct option thanks to अनुस्वारस्य ययि परसवर्णः

However we have a strict mode, and a (default) non-strict mode, so this might make sense for the non-strict mode. 

Thoughts, @vvasuki @avinashvarna @codito ?

**Comment by vvasuki** [comment]
It is quite alright not to have a non-strict mode at all, and leave it up to the user to not use lazy anusvAra-s (which can be autofixed using https://sanskrit-coders.github.io/indic_transliteration/build/html/indic_transliteration_deduplication.html ). If you want to provide and maintain an additional non-strict layer - that's fine too, you could use the same facility internally.

**Comment by avinashvarna** [comment]
I think supporting it in non-strict mode is a good idea - ma. I like @vvasuki's suggestion to use the function already available in indic_transliteration.

@vvasuki , is there any plan to support other encoding schemes besides itrans? It could be as simple as writing a wrapper to convert the user input to itrans, fix anusvAras and convert back.

**Comment by vvasuki** [comment]
> @vvasuki , is there any plan to support other encoding schemes besides itrans? It could be as simple as writing a wrapper to convert the user input to itrans, fix anusvAras and convert back.

True - which is why I didn't make such a wrapper part of the library (and perhaps the only other user @drdhaval2785  didn't care). If you think a wrapper is useful - just send a pull request (include a test case though).

**Comment by kmadathil** [comment]
We already implement a non-strict mode thanks to #56. I've implemented this using @vvasuki 's method. Thanks!

**Comment by kmadathil** [comment]
$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split BujaMgatuMgamAlikAm 
Interpreting input loosely (strict_io set to false)
Input String: BujaMgatuMgamAlikAm
Input String in SLP1: BujaNgatuNgamAlikAm
Start Split
End DAG generation
End pathfinding 1544819900.8538425
Splits:
[BujaNga, tuNga, mAlikAm]
[Bujam, ga, tuNga, mAlikAm]
[BujaNga, tuNgam, Ali, kAm]
[BujaNga, tuNga, mAlika, am]
[BujaNga, tuNga, mAlikA, am]
[BujaNga, tuNga, mAlika, Am]
[BujaNga, tuNga, ma, alikAm]
[BujaNga, tuNga, mAlikA, Am]
[BujaNga, tuNga, mA, alikAm]
[BujaNga, tuNga, mAli, kAm]
-----------
Performance
Time for graph generation = 0.292648s
Total time for graph generation + find paths = 0.295040s

**Comment by vvasuki** [comment]
@kmadathil Can you please update your indic_transliteration module and use the following call instead:
`sanscript.SCHEMES[sanscript.ITRANS].fix_lazy_anusvaara("taM jitvA")`

**Comment by kmadathil** [comment]
Done.

**Comment by kmadathil** [comment]
@vvasuki - did you abandon py27 on this release?

**Comment by vvasuki** [comment]
Several releases ago, actually.

**Comment by kmadathil** [comment]
This feature will be unsupported in 2.7, but won't result in a crash.
