### ISSUE TITLE
BujaNgatuNgamAlikAm_split

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#104]
No need to bifurcate mAlikAm to mAli kAm.

{"input":"BujaNgatuNgamAlikAm","devanagari":"भुजङ्गतुङ्गमालिकाम्","splits":[["भुजङ्ग","तुङ्ग","मालि","काम्"],["भुजङ्ग","तुङ्ग","मा","अलि","काम्"]]}

**Comment by kmadathil** [comment]
$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split BujaNgatuNgamAlikAm  
Input String: BujaNgatuNgamAlikAm
Input String in SLP1: BujaNgatuNgamAlikAm
Start Split
End DAG generation
End pathfinding 1544669147.3948016
Splits:
[BujaNga, tuNga, mAlikAm]
[Bujam, ga, tuNga, mAlikAm]
[BujaNga, tuNgam, Ali, kAm]
[BujaNga, tuNga, mAlikA, Am]
[BujaNga, tuNga, ma, alikAm]
[BujaNga, tuNga, mAlikA, am]
[BujaNga, tuNga, mA, alikAm]
[BujaNga, tuNga, mAli, kAm]
[BujaNga, tuNga, mAlika, am]
[BujaNga, tuNga, mAlika, Am]

**Comment by kmadathil** [comment]
As you can see, the first split is the expected one. However, the online version shows the splits that @drdhaval2785 has reported. This means that it's using the inria lexical lookup instead of "combined". Need to check why

**Comment by avinashvarna** [comment]
Pulled the latest code and restarted the web service. Should work correctly now:
https://api.vedavaapi.org/py_skt_parser/sanskrit_parser/v1/splits/BujaNgatuNgamAlikAm
{
  "input": "BujaNgatuNgamAlikAm",
  "devanagari": "भुजङ्गतुङ्गमालिकाम्",
  "splits": [
    [
      "भुजङ्ग",
      "तुङ्ग",
      "मालिकाम्"
    ],
<snip>
