### ISSUE TITLE
जटाकटाहसम्भ्रमभ्रमन्निलिम्पनिर्झरी issues

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#106]
1. BramannilimpanirJarI can not split as Bramam+nilimpanirJarI. Rather I am curious to see any conversion from m+n to nn.
2. Keeping nilimpanirJarI as a whole word is a bit off. I feel that MW may have this samAsa as a word. I have worked with MW data of Cologne earlier. Key2 has such words split like nilimpa-nirJarI. We should try to use key2 rather than key1 for MW. 

{"input":"जटाकटाहसम्भ्रमभ्रमन्निलिम्पनिर्झरी","devanagari":"जटाकटाहसम्भ्रमभ्रमन्निलिम्पनिर्झरी","splits":[["जटा","कटाह","सम्भ्रम","भ्रमम्","निलिम्पनिर्झरी"],["जटा","कटाह","सम्भ्रम","भ्रमत्","निलिम्पनिर्झरी"],["जटा","कटाह","सम्भ्रम","भ्रमन्","निलिम्पनिर्झरी"],["ज","टा","कटाह","सम्भ्रम","भ्रमम्","निलिम्पनिर्झरी"],["जटा","कट","आहसम्","भ्रम","भ्रमम्","निलिम्पनिर्झरी"],["जटा","कटाह","सम्","भ्रम","भ्रमत्","निलिम्पनिर्झरी"],["जटा","कटाह","सम्भ्रम","भ्रमम्","निलिम्प","निर्झरी"],["जटा","कटाह","सम्भ्रम","भ्रमत्","निलिम्प","निर्झरी"],["जटा","कटाह","सम्भ्रम","भ्रमन्","निलिम्प","निर्झरी"],["जट","आ","कटाह","सम्भ्रम","भ्रमम्","निलिम्पनिर्झरी"]]}

**Comment by kmadathil** [comment]
>BramannilimpanirJarI can not split as Bramam+nilimpanirJarI.  

m->anusvAra->parasavarna . What prevents this?

**Comment by kmadathil** [comment]
I'll request @avinashvarna to respond on point 2.

**Comment by avinashvarna** [comment]
The forms from MW are taken from this project by Arun that already had scraped them - https://github.com/sanskrit/data. I don't have the bandwidth to investigate what it would take to convert it to a different key provided by MW. 

But is it really such a big problem from a use case perspective? As long as a user can look up a word in a specified dictionary and understand the meaning, I would argue that the goal of the splitter is achieved.

**Comment by drdhaval2785** [comment]
Ok. If linking the user to a dictionary word is the expected output, I do not see much value in pressing this further. Dropping the issue.
