### ISSUE TITLE
धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर issues

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#107]
1. vilAsaH + banDu is not valid split. 
If aH is followed by soft consonants (hash), it gets converted to 'o'. Would give vilAso banDu

{"input":"धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर","devanagari":"धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर","splits":[["धराधरेन्द्र","नन्दिनी","विलासः","बन्धु","बन्धुर"],["धराधरेन्द्र","नन्दिनी","विल","असबन्धु","बन्धुर"],["धराधरेन्द्र","नन्दिनी","विलास","बन्धु","बन्धुर"],["धराधर","इन्द्र","नन्दिनी","विलासः","बन्धु","बन्धुर"],["धराधरेन्द्र","नम्","दिनी","विल","असबन्धु","बन्धुर"],["धराधरेन्द्र","नन्दिनी","विलासः","बम्","धु","बन्धुर"],["धराधरेन्द्र","नन्दिनी","विलासः","बन्धु","बन्धु","र"],["धराधरेन्द्र","नन्दिनी","विल","अ","सबन्धु","बन्धुर"],["धराधरेन्द्र","नन्दिनी","विल","असबन्धु","बन्धु","र"],["धराधरेन्द्र","नन्दिनी","वि","ल","असबन्धु","बन्धुर"]]}

**Comment by avinashvarna** [comment]
This is happening due to the rule added to handle cases like सः बन्धुः -> स बन्धुः. Unfortunately, the sandhi module does not have a mechanism to say that an entire word must match, so it sees the सबन्धु  in विलासबन्धु and splits it as well.
Handling this properly would require new functionality in the sandhi module.

**Comment by drdhaval2785** [comment]
If that is too much of hassle, leave it. Keep the issue open, so that it remains noted as Known Issue.

If not much of a hassle, add the new facility.

**Comment by kmadathil** [comment]
Perhaps a second "forward" pass could be added to prune splits.

**Comment by avinashvarna** [comment]
The forward pass wouldn't help in this particular case, since the forward pass doesn't know that सः has to be a full word either. So it would see विला*सः* बन्धुः and consider विलासबन्धुः a valid result.

**Comment by kmadathil** [comment]
In this case, perhaps the rule can be rewritten such that "स/एष" are in the initial position (no prefix string). Not sure if you have a way to do that.

More generally, we could run a forward pass *after* we compute valid splits,  at which point, we have all word boundaries. I seem to remember us parking this option to fix some corner cases of something (Natvam, if I remember)

**Comment by kmadathil** [comment]
```
(fix_107)$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर
Interpreting input loosely (strict_io set to false)
Input String: धराधरेन्द्रनन्दिनीविलासबन्धुबन्धुर
Input String in SLP1: DarADarendranandinIvilAsabanDubanDura
Start Split
End DAG generation
End pathfinding 1555109478.8291097
Splits:
[DarADarendra, nandinI, vilAsa, banDu, banDura]
[DarAH, Dara, indra, nandinI, vilAsa, banDu, banDura]
[DarADarendra, nandin, I, vilAsa, banDu, banDura]
[DarADarendra, nandinI, vilAsa, banDu, banDuH, a]
[DarADarendra, nandinI, vilAsa, banDu, banDu, ra]
[DarAH, Dara, indra, nandinI, vilAsa, banDu, banDu, ra]
[DarAH, DarA, indra, nandinI, vilAsa, banDu, banDu, ra]
[DarADarendra, nandin, I, vilAsa, banDu, banDu, ra]
[DarADara, indra, nandinI, vilAsa, banDu, banDu, ra]
[DarA, Dara, indra, nandinI, vilAsa, banDu, banDu, ra]
-----------
Performance
Time for graph generation = 1.093025s
Total time for graph generation + find paths = 1.144632s
```

**Comment by kmadathil** [comment]
@avinashvarna - please look into the commit above when you have time. This is the first idea in my comment above - implement a way to match a full word only. The rule now is ^[स,एष][स्] + 

I also noticed something, which I didn't change, the rule had + [*अल् - अ] . Shouldn't it be + [*अल्], so we can implement saH + atra -> sa atra?

**Comment by avinashvarna** [comment]
सः + अत्र = सोऽत्र, which is why the rule has [*अल् - अ]
I will take a look at the fix_107 branch over the weekend.

**Comment by kmadathil** [comment]
I think I haven't got the full hang of your syntax then. I misunderstood the `-` as a range indicator (and couldn't parse what that meant) rather than a subtraction. I'll spend some time reading sandhi.py in more detail then. :-)

**Comment by kmadathil** [comment]
Ok, I think I am a bit confused there. Let me go over this once more.

**Comment by avinashvarna** [comment]
The minus is indeed a subtraction like a set difference operator. *अल् = {अ, इ, उ, ..., ह्}, अ = {अ}, so [*अल् - अ] = {इ, उ, ..., ह्}. There are no range operators in the syntax. I can add more comments in the rules files if it is still confusing. (It's possible that I didn't update the comments as we developed more advanced ways of writing the rules).

**Comment by avinashvarna** [comment]
The fix seems OK to me. The two tests that are failing on travis could be marked as expected to fail, since the split in the file is misleading (or we can fix it in the file). I think we can add a specific test for this case if necessary. Thanks for making the change!

**Comment by kmadathil** [comment]
Handled failing tests as above.
