### ISSUE TITLE
चकोरबन्धुशेखरः issues

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#109]
Does not yield any result. Seems to have to do with our H to s conversion. BUH also did nof yield result in an earlier issue.

**Comment by kmadathil** [comment]
$ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split  "chakorabandhushekharaH"
Input String: chakorabandhushekharaH
Input String in SLP1: cakorabanDuSeKaraH
Start Split
End DAG generation
End pathfinding 1545068770.7840314
Splits:
[cakora, banDu, SeKaraH]
[caka, uH, abanDu, SeKaraH]
[cakora, bam, Du, SeKaraH]
[cakora, banDu, Se, KaraH]
[cakaH, aH, abanDu, SeKaraH]
[caka, ura, banDu, SeKaraH]
[ca, koH, abanDu, SeKaraH]
[cakaH, ra, banDu, SeKaraH]
[caka, uH, abanDu, SeKaraH]
[ca, kora, banDu, SeKaraH]
-----------
Performance
Time for graph generation = 0.301946s
Total time for graph generation + find paths = 0.304219s

**Comment by kmadathil** [comment]
I've closed the other issue, but I'll leave this open to discuss why @drdhaval2785 isn't seeing the same result as us.

**Comment by avinashvarna** [comment]
Fixed and API is updated as well:
https://api.vedavaapi.org/py_skt_parser/sanskrit_parser/v1/splits/chakorabandhushekharaH
https://api.vedavaapi.org/py_skt_parser/sanskrit_parser/v1/splits/pIThabhUH
