### ISSUE TITLE
Having an issue with inriaxmlwrapper

### ISSUE THREAD

**Issue by pmshukla** [kmadathil/sanskrit_parser#113]
I got the following error while trying to parse the sample from documentation:-

%Traceback (most recent call last):
  File "sanskrit.py", line 2, in <module>
    from sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer import SanskritLexicalAnalyzer
  File "/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/lexical_analyzer/SanskritLexicalAnalyzer.py", line 125, in <module>
    class SanskritLexicalAnalyzer(object):
  File "/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/lexical_analyzer/SanskritLexicalAnalyzer.py", line 131, in SanskritLexicalAnalyzer
    forms  = ixw.InriaXMLWrapper()
  File "/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 96, in __init__
    self._load_forms()
  File "/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 143, in _load_forms
    self.forms = pickle.load(fd)
EOFError%

**Comment by kmadathil** [comment]
@pmshukla : looks like your pickle file isn't being loaded. Can you do an ls on it?
$ ls -l ~/.sanskrit_parser/data/*

**Comment by pmshukla** [comment]
I'm actually not able to get the data folder in my sanskrit_parser

` ls -l ~/.sanskrit_parser/data/*`

and for only sanskrit_parser 

`pranav@pranav-Aspire-E1-572G:~$ ls -l /home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/*
-rw-rw-r-- 1 pranav pranav    8 Apr  4 17:50 /home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/__init__.py
-rw-rw-r-- 1 pranav pranav  176 Apr  4 17:52 /home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/__init__.pyc

/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/base:
total 64
-rw-rw-r-- 1 pranav pranav    0 Apr  4 17:50 __init__.py
-rw-rw-r-- 1 pranav pranav  157 Apr  4 17:52 __init__.pyc
-rw-rw-r-- 1 pranav pranav 6327 Apr  4 17:50 maheshvara_sutra.py
-rw-rw-r-- 1 pranav pranav 5991 Apr  4 17:52 maheshvara_sutra.pyc
-rw-rw-r-- 1 pranav pranav 5668 Apr  4 17:50 MaheshvaraSutras.py
-rw-rw-r-- 1 pranav pranav 5265 Apr  4 17:52 MaheshvaraSutras.pyc
-rw-rw-r-- 1 pranav pranav 5962 Apr  4 17:50 sanskrit_base.py
-rw-rw-r-- 1 pranav pranav 3945 Apr  4 17:50 SanskritBase.py
-rw-rw-r-- 1 pranav pranav 6403 Apr  4 17:52 sanskrit_base.pyc
-rw-rw-r-- 1 pranav pranav 4521 Apr  4 17:52 SanskritBase.pyc

/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/lexical_analyzer:
total 120
-rw-rw-r-- 1 pranav pranav  3413 Apr  4 17:50 __init__.py
-rw-rw-r-- 1 pranav pranav  3598 Apr  4 17:52 __init__.pyc
-rw-rw-r-- 1 pranav pranav 16918 Apr  4 17:50 sandhi.py
-rw-rw-r-- 1 pranav pranav 15498 Apr  4 17:52 sandhi.pyc
drwxrwxr-x 2 pranav pranav  4096 Apr  4 17:52 sandhi_rules
-rw-rw-r-- 1 pranav pranav 17629 Apr  4 17:50 sanskrit_lexical_analyzer.py
-rw-rw-r-- 1 pranav pranav 13657 Apr 12 07:15 SanskritLexicalAnalyzer.py
-rw-rw-r-- 1 pranav pranav 17023 Apr  4 17:52 sanskrit_lexical_analyzer.pyc
-rw-rw-r-- 1 pranav pranav 14429 Apr 12 07:16 SanskritLexicalAnalyzer.pyc

/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/morphological_analyzer:
total 72
-rw-rw-r-- 1 pranav pranav  2518 Apr  4 17:50 __init__.py
-rw-rw-r-- 1 pranav pranav  2709 Apr  4 17:52 __init__.pyc
-rw-rw-r-- 1 pranav pranav 13292 Apr  4 17:50 sanskrit_morphological_analyzer.py
-rw-rw-r-- 1 pranav pranav 12319 Apr  4 17:50 SanskritMorphologicalAnalyzer.py
-rw-rw-r-- 1 pranav pranav 13176 Apr  4 17:52 sanskrit_morphological_analyzer.pyc
-rw-rw-r-- 1 pranav pranav 12628 Apr  4 17:52 SanskritMorphologicalAnalyzer.pyc

/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/rest_api:
total 32
-rw-rw-r-- 1 pranav pranav 3103 Apr  4 17:50 api_v1.py
-rw-rw-r-- 1 pranav pranav 4392 Apr  4 17:52 api_v1.pyc
-rw-rw-r-- 1 pranav pranav 1578 Apr  4 17:50 flask_helper.py
-rw-rw-r-- 1 pranav pranav 1977 Apr  4 17:52 flask_helper.pyc
-rw-rw-r-- 1 pranav pranav    0 Apr  4 17:50 __init__.py
-rw-rw-r-- 1 pranav pranav  161 Apr  4 17:52 __init__.pyc
-rw-rw-r-- 1 pranav pranav  988 Apr  4 17:50 run.py
-rw-rw-r-- 1 pranav pranav 1474 Apr  4 17:52 run.pyc

/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/util:
total 136
-rw-rw-r-- 1 pranav pranav  4296 Apr  4 17:50 DhatuWrapper.py
-rw-rw-r-- 1 pranav pranav  5446 Apr  4 17:52 DhatuWrapper.pyc
-rw-rw-r-- 1 pranav pranav     0 Apr  4 17:50 __init__.py
-rw-rw-r-- 1 pranav pranav   157 Apr  4 17:52 __init__.pyc
-rw-rw-r-- 1 pranav pranav  6646 Apr  4 17:50 inriatagmapper.py
-rw-rw-r-- 1 pranav pranav 10991 Apr  4 17:52 inriatagmapper.pyc
-rw-rw-r-- 1 pranav pranav  8821 Apr 12 07:21 inriaxmlwrapper.py
-rw-rw-r-- 1 pranav pranav  8821 Apr 12 07:20 inriaxmlwrapper.py~
-rw-rw-r-- 1 pranav pranav  9489 Apr 12 07:21 inriaxmlwrapper.pyc
-rw-rw-r-- 1 pranav pranav  1308 Apr  4 17:50 lexical_lookup_factory.py
-rw-rw-r-- 1 pranav pranav  2348 Apr  4 17:52 lexical_lookup_factory.pyc
-rw-rw-r-- 1 pranav pranav  1679 Apr  4 17:50 lexical_lookup.py
-rw-rw-r-- 1 pranav pranav  2606 Apr  4 17:52 lexical_lookup.pyc
-rw-rw-r-- 1 pranav pranav  2714 Apr  4 17:50 lexical_scorer.py
-rw-rw-r-- 1 pranav pranav  3829 Apr  4 17:52 lexical_scorer.pyc
-rw-rw-r-- 1 pranav pranav  1707 Apr  4 17:50 normalization.py
-rw-rw-r-- 1 pranav pranav  2484 Apr  4 17:52 normalization.pyc
-rw-rw-r-- 1 pranav pranav  2449 Apr  4 17:50 rest_api.py
-rw-rw-r-- 1 pranav pranav  3688 Apr  4 17:52 rest_api.pyc
-rw-rw-r-- 1 pranav pranav  7536 Apr  4 17:50 sanskrit_data_wrapper.py
-rw-rw-r-- 1 pranav pranav  8634 Apr  4 17:52 sanskrit_data_wrapper.pyc`

and when doing for 
`~/.sanskrit_parser/data/*`
`pranav@pranav-Aspire-E1-572G:~$ ls -l /home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/data/*
ls: cannot access '/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/data/*': No such file or directory`

**Comment by pmshukla** [comment]
@kmadathil 
 Isn't the error related to the base URL `https://github.com/drdhaval2785/inriaxmlwrapper/raw/master/`
in inriaxmlwrapper.py which is not found at the moment

**Comment by avinashvarna** [comment]
Looks like the URL has indeed changed. We will have to update that. But that should have caused an HTTP exception. 

If the pickle file does not exist in `~/.sanskrit_parser/data`, execution should not reach line 143. Can you please double check that there is no file in `~/.sanskrit_parser/data`?  Note that `/home/pranav/.local/lib/python2.7/site-packages/sanskrit_parser/data/*` is not the same as `~/.sanskrit_parser/data` unless you have set up some symlinks.

**Comment by kmadathil** [comment]
Also, if that's the issue, there's a workaround using the option if you're running from the command line 
`--lexical-lookup sanskrit_data `

or, if you're using the python snippets

```
analyzer = SanskritLexicalAnalyzer("sanskrit_data")
```

Please let us know if it works for you.

**Comment by kmadathil** [comment]
@avinashvarna  @drdhaval2785

Looks like the inriaxmlwrapper files have vanished from github? If we have the xml files available, we can host them here and change the url.

**Comment by avinashvarna** [comment]
The files are still available in the repo - https://github.com/drdhaval2785/inriaxmlwrapper/. The links to the raw content has changed to https://raw.githubusercontent.com/drdhaval2785/inriaxmlwrapper/master/ instead of `https://github.com/drdhaval2785/inriaxmlwrapper/raw/master/`

**Comment by kmadathil** [comment]
PR created, please review

**Comment by pmshukla** [comment]
@avinashvarna ok got it as you said "data" folder does exist and output for `ls -l` is 
pranav@pranav-Aspire-E1-572G:~/.sanskrit_parser/data$` ls -l
total 38408
-rw-rw-r-- 1 pranav pranav        0        Apr 12 07:21 _all.pickle
-rw-rw-r-- 1 pranav pranav   628134   Apr 11 10:45 SL_adverbs.xml
-rw-rw-r-- 1 pranav pranav        0        Apr 11 10:45 SL_final.xml
-rw-rw-r-- 1 pranav pranav 20749483 Apr 11 10:45 SL_nouns.xml
-rw-rw-r-- 1 pranav pranav        0        Apr 11 10:46 SL_parts.xml
-rw-rw-r-- 1 pranav pranav        0        Apr 11 10:46 SL_pronouns.xml
-rw-rw-r-- 1 pranav pranav 17946578 Apr 11 10:45 SL_roots.xml
-rw-rw-r-- 1 pranav pranav        0        Apr 11 10:46 SL_upasargas.xml

**Comment by pmshukla** [comment]
> Also, if that's the issue, there's a workaround using the option if you're running from the command line
> `--lexical-lookup sanskrit_data `
> 
> or, if you're using the python snippets
> 
> ```
> analyzer = SanskritLexicalAnalyzer("sanskrit_data")
> ```
> 
> Please let us know if it works for you.

For python code I have already used as stated by you
`analyzer = SanskritLexicalAnalyzer("sanskrit_data")`

**Comment by avinashvarna** [comment]
Looks like the first time you ran it, the files got created with 0 size due to the broken link. Once PR #114 is merged, please update the code, `rm -rf ~/.sanskrit_parser/data` and rerun.

**Comment by pmshukla** [comment]
@avinashvarna @kmadathil 
I ran the sanskritlexicalanalyzer.py with the link in above description which correctly generated the pickle file which can be accessed.

**Comment by kmadathil** [comment]
Merged. 
@pmshukla: Please remove the old code and `~/.sanskrit_parser/data` directory, install the new code, and please check if you're able to run. If that works, we can close this issue. Thanks for reporting this issue!

**Comment by pmshukla** [comment]
@kmadathil 
Yup done it and its running
