### ISSUE TITLE
Programmatic usage - better wrapper functions

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#120]
> The process of getting parses needs to be wrapped in a simple function that can then be used by someone who imports the library, the CLI, and the REST API. If I understand correctly, currently, a user would need to call SandhiAnalyzer to get the splits, create a VakyaGraph for each split and iterate over the parses. What do you think about wrapping all this into a single function that yields parses?

Until we merge the process of generating splits and parses, we will probably need two wrapper functions
1. Wrapper function that yields splits
2. Wrapper function that yields parses given a split

@avinashvarna , @vvasuki @codito  - thoughts?

**Comment by avinashvarna** [comment]
From the module user point of view;, I think an ideal API would allow code like this:
```python
from sanskrit_parser import Parser

parser = Parser('devadattogrAmaMgacCati')
for split in parser.splits(max_results=10):
    print(f'Parses for {split}:')
    for parse_result in split.parse(max_results=15):
         print(f'{parse_result}')
```

The intermediate objects returned by `parser.splits()` and `split.parse()` can be `LexicalGraph`, `VakyaGraph` or something else entirely, as long as a simple API is exposed to convert to strings, serialize to JSON with different encodings (SLP1/Devanagari), etc., that a typical user might need. This way, the user doesn't need to deal with different kinds of data structures. We could treat the code required to create the CLI and the REST API client as what a typical user would need.

To avoid heavy pre-computations, `parser.splits()` and `split.parse()` can `yield` results as they are available.

**Comment by avinashvarna** [comment]
Or the following slight variation, which is marginally clearer:
```python
from sanskrit_parser import Parser

parser = Parser(lexical_lookup=..., other_options=...)
parse_result = parser.parse('devadattogrAmaMgacCati')
for split in parse_result.splits(max_results=10):
    print(f'Parses for {split}:')
    for parse_result in split.parse(max_results=15):
         print(f'{parse_result}')
```

I can take a stab at creating such an interface for review if there are no objections.

**Comment by kmadathil** [comment]
Looks good, please go ahead! Thanks!

**Comment by avinashvarna** [comment]
Please take a look at commit 19417ab. It has an implementation for the above interface, that will work to unify the CLI and REST API. Previously, the output_encoding is hard-coded to devanagari for REST API and SLP1 for CLI. This API implementation gives us the flexibility to support any encoding, and also allows the user of the module in a programmatic setting to specify any desired supported encoding.

`api.py` can be run for a quick example. Note that if your terminal doesn't support unicode output, the example will give a `UnicodeDecodeError` (I ran it in an ipython window), but the main idea should be clear from the code.

**Comment by avinashvarna** [comment]
In general, I think we need to make a concerted effort to use classes and other recognizable structures more often. Coming back to this project after a while, it took me a long time to figure out what the format for tags, etc. was, because most of them are just lists and tuples, which don't carry any object information with them.

**Comment by kmadathil** [comment]
Took a quick look through the code - looks good. I wonder if you're compensating for some underlying deficiencies in our class design, though. If you had carte blanche, would you keep the underlying classes or merge them into your api classes somehow? 
For example, it seems to me that LexicalSandhiAnalyzer could be renamed Parser, and your parse method can be added in. ParseTag could  be what our lexical_lookup classes return.

**Comment by avinashvarna** [comment]
Yes, I agree that our underlying classes could be better designed to directly support this API. (That is what I had in mind in my previous comment - though I could have been clearer). We could still make the changes. It would be a slightly larger redesign effort though.

**Comment by kmadathil** [comment]
Fair. I've made a couple of changes and pushed to api, please take a look (we can revert if you don't like them)
1. input_encoding and output_encoding were asymmetric in your implementation - I've made them symmetric ("SLP1" vs "slp1")
2. Added api.Parser to sanskrit_parser/__init__.py, so we can `from sanskrit_parser import Parser`

I need to see if we can use the same api for the command line script instead of the current method. Things that are not obvious are the intermediate times that are being reported (for split, path, parse etc.) and how to handle the graphs.

**Comment by avinashvarna** [comment]
I'll take a look at the changes, but some quick comments:
> Added api.Parser to sanskrit_parser/init.py, so we can from sanskrit_parser import Parser

This was my intention also. I wanted to make sure we agreed this was a good path forward before I made too many changes

> Things that are not obvious are the intermediate times that are being reported (for split, path, parse etc.) and how to handle the graphs.

We should not mix debugging info with real output. IMHO, not too many users of the CLI will care about intermediate times. Such info should really be logged with level `debug`, and if a developer wanted to look at the times, he can enable `--debug`, and look at the log. Ditto for the graphs. Maybe useful for us, but do we really expect users to install pygraphviz (which is non-trivial on Windows), convert the dot to an image and look at it? We can just put the dot format of all the parses in the debug log. If needed, we can write a convenience script that searches the debug log, parses/extracts the dot and writes it out to separate files for each of the parses.

**Comment by kmadathil** [comment]
Makes sense. I was coming at it from the pov of replacing the current main() in vakya_analyzer with this api. 

>  Added api.Parser to sanskrit_parser/init.py, so we can from sanskrit_parser import Parser

That was just one import, btw. I haven't moved code.

**Comment by kmadathil** [comment]
I've added an l3api branch with `vakya_analyzer.main` modified to use the new api. Please take a look. The question to answer here is if it is worth using the api for the command line scripts as well. To be able to do that, I've added a few `logger.debug` calls inside the api.

**Comment by avinashvarna** [comment]
> I've added an l3api branch with `vakya_analyzer.main` modified to use the new api. Please take a look.

I may be a bit biased, but personally, I feel that the `vakya_analyzer.main` code is much cleaner now.

> The question to answer here is if it is worth using the api for the command line scripts as well. 

I definitely think so. This allows easier maintainability. If we change something underneath the hood, but the external API is the same, then none of the CLI, REST API files would need to change. Currently, we need to go change each of them - Like adding the `jedge, jnode` methods now.

> To be able to do that, I've added a few logger.debug calls inside the api.

These are fine.  However, I don't think any module should set up logging in `__init__.py` [here](https://github.com/kmadathil/sanskrit_parser/blob/67acc1ab452a8af3a6b08ab90d5bfe47effd2c7f/sanskrit_parser/__init__.py#L83) unless it is qualified with a `if __name__ == "__main__":`. Otherwise, any other script that just does `import sanskrit_parser` will start creating log files and console logging. Might be better to move them to the script instead.

In the long term, if you think it makes more sense to merge the API into the classes themselves, maybe we should do them sooner rather than later (i.e. now).

**Comment by kmadathil** [comment]
> ... I feel that the vakya_analyzer.main code is much cleaner now.

I agree. I'll merge into l3new (and eventually master) and delete this branch.

> However, I don't think any module should set up logging in __init__.py

There are two parts to this - setting up the logger itself and setting up handlers. I think setting up the logger is necessary (so that there's a logger at the sanskrit_parser level. I agree that setting up handlers is probably excessive. Perhaps I could wrap them in functions which could then be called from any enclosing script? 
```
import sanskrit_parser
sanskrit_parser.enableFileLog(file="SanskritParser.log", format=yyy, level=logger.DEBUG)
sanskrit_parser.enableConsoleLog(format=fff, level=logger.INFO)
```

**Comment by avinashvarna** [comment]
> Perhaps I could wrap them in functions which could then be called from any enclosing script?

I wonder whether these are functions that another script that is importing `sanskrit_parser` would want to use? IMHO, the answer is mostly no. Usually, the task of configuring the logging handlers is the responsibility of the script that is being executed. Hence, I think putting them in `scripts/sanskrit_parser` makes more sense. 

On the other hand, implementing a solution for #121 may require them to be somewhere within the module. Maybe we could do as you propose for now, and once we figure out #121, we can decide the right place to put them.

**Comment by kmadathil** [comment]
I think we can close this issue. @avinashvarna  - please look at the current state of l3new, and if it looks ok, I'll merge to master. If the current state of logging is insufficient, we can open another issue for that.

**Comment by avinashvarna** [comment]
Will do it soon (by this weekend at the latest).

**Comment by avinashvarna** [comment]
Sorry for the delay. The `l3new` branch looks good. I made some minor changes such as using `pydot` instead of `pygraphviz` which is easier to install on windows using `conda`. 

I am not in favor of enabling file logging if the user has not enabled debug (https://github.com/kmadathil/sanskrit_parser/blob/66174aea561577e863f264207b36514b2e3db0d2/sanskrit_parser/cmd_line.py#L211), since it creates a bunch of log files in whichever directory the user runs the script from, and since the same info is already printed to the console. If this is something you feel strongly about, we can agree to disagree on this point and leave it as it is.

I think we can merge it into master and release a new version to pypi as well.

**Comment by kmadathil** [comment]
I've changed logging so that file logs get written only when --debug is selected. My preference for always logging is idiosyncratic, and will not translate to most users, so I agree with your preference.

Merged to master and released to PyPI
