### ISSUE TITLE
Setuptools recommends using entrypoints rather than scripts

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#121]
We have scripts/sanskrit_parser, which is deployed by setuptools. Can we move to entrypoints, which are more portable as per setuptools.

**Comment by kmadathil** [comment]
@avinashvarna - does 4b8c139 solve the issue?

**Comment by avinashvarna** [comment]
Closing as  4b8c139 and 05382e8 together solve this issue
