### ISSUE TITLE
"No Module named sanskrit_parser.parser"

### ISSUE THREAD

**Issue by pmshukla** [kmadathil/sanskrit_parser#125]
from sanskrit_parser.parser.sandhi_analyzer import LexicalSandhiAnalyzer
is giving me an error as "No Module named sanskrit_parser.parser".
When i check the site packages there is no folder named parser which i think causes the error.

**Comment by avinashvarna** [comment]
Which version of the package are you using?
This import:
```python
from sanskrit_parser.parser.sandhi_analyzer import LexicalSandhiAnalyzer
```
will only work in the latest version that is currently in git. Can you please update to the latest version? E.g. using
```
pip install -U git+https://github.com/kmadathil/sanskrit_parser
```

We will probably make some API changes soon to make the interface easier to use (as described in #120) and release a new version to pypi as well. If you prefer, you could just wait till we release a new package that can directly be installed with pip

**Comment by kmadathil** [comment]
Please reinstall from PyPI - the new release will bring the package and github documentation back in sync.
