### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#140]
```
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: SELECT nominal_ending.id AS nominal_ending_id, nominal_ending.name AS nominal_ending_name, nominal_ending.stem_type AS nominal_ending_stem_type, nominal_ending.gender_id AS nominal_ending_gender_id, nominal_ending.case_id AS nominal_ending_case_id, nominal_ending.number_id AS nominal_ending_number_id, nominal_ending.compounded AS nominal_ending_compounded
FROM nominal_ending]
```
Reported on email by Vinodh Rajan

**Comment by kmadathil** [comment]
Repro'ed by fresh install in a virtualenv after clearing ~/.sanskrit_parser

Fixed by
1. Uploading new version onto PyPI
2. Clearing ~/.sanskrit_parser/*
3. Fresh install of pip install sanskrit_parser in a virtualenv.

**Comment by kmadathil** [comment]
The `~/.sanskrit_parser/` directory is a source of pain. I suggest we
1. Explicitly tell the user when we are downloading/caching stuff in that directory
2. Mark the version used to create data and prompt the user to recreate or not if the version changes 
Thoughts? @avinashvarna

**Comment by avinashvarna** [comment]
I think #127 is the solution. It will be part of the pip package, and a pip remove will clear it and an install will overwrite it. They will not go out of sync.

**Comment by kmadathil** [comment]
Closing
