### ISSUE TITLE
UI not working

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#147]
UI at https://kmadathil.github.io/sanskrit_parser/ui/index.html is not returning any results.
If I chose `Analyse Pada` and write 'Davalasya' in the text box and click 'Go',
Nothing is returned.

Console shows that a call to https://sktparserapi.madathil.org/sanskrit_parser/v1/tags/Davalasya is made, but no response comes back.

**Comment by kmadathil** [comment]
I have disabled the UI backend since I didn't see any usage, and the server
is paid. I'll enable if there is interest

**Comment by drdhaval2785** [comment]
I do not have any preference for the UI.
But I was exploring it, because the CLI also did not work for me.
See #146 

If that is fixed, I have no interest in the UI working.

**Comment by kmadathil** [comment]
Can you upgrade to Python 3.7? I don't think dataclasses is available for 3.6

**Comment by drdhaval2785** [comment]
Works on CLI with python3.9.1. 

README needs to be updated to remove the link to the UI, so that unsuspecting people do not think that the code / UI is broken.

**Comment by kmadathil** [comment]
Will close after README change.
