### ISSUE TITLE
Add notebooks that can be run on binder/colab for interactive exploration?

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#158]
I think it would be a good idea to add at least one jupyter notebook that shows how to use the parser API. The notebook can be run on cloud based services such as binder or colab, for interactive exploration. I actually initiated a [binder build](https://mybinder.org/v2/gh/kmadathil/sanskrit_parser/master) and created a notebook. Unfortunately, I didn't realize that it doesn't save the notebook. Shouldn't take too long to recreate a notebook with a few simple examples.

**Comment by kmadathil** [comment]
Good idea.

**Comment by avinashvarna** [comment]
Added an Ipython notebook as an [example](https://github.com/kmadathil/sanskrit_parser/blob/api_changes/examples/basic_example.ipynb). Need to add binder badge, etc.

**Comment by kmadathil** [comment]
This is nice!

**Comment by avinashvarna** [comment]
Closed via #163
