### ISSUE TITLE
Different Transliteration Schemes for Input

### ISSUE THREAD

**Issue by gasyoun** [kmadathil/sanskrit_parser#165]
Can the script tolerate not only `sambhūyasamutthāna`, but also `saṁbhūyasamutthāna`?

![issue](https://user-images.githubusercontent.com/80761/112273303-4113e680-8c8e-11eb-867e-5dbf5ed679e9.JPG)

**Comment by kmadathil** [comment]
We can handle most Brahmi-derived scripts and some transliterations such as SLP1, ITRANS, IAST, HK, and Velthuis.  Which transliteration uses ṁ?

**Comment by avinashvarna** [comment]
This is valid IAST. We depend on the indic_transliteration package to handle the transliteration. May need to see if there is some error in the package, or our wrapper around it.

**Comment by kmadathil** [comment]
[IAST](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) uses ṃ, not ṁ

**Comment by avinashvarna** [comment]
Oops. Sorry. didn't notice the dot above vs below. It looks like it represents a different character in ISO - https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration#Comparison_with_ISO_15919

**Comment by gasyoun** [comment]
> It looks like it represents a different character in ISO

Yes, and it's quite popular. IAST is not as IAST everywhere.

> Which transliteration uses ṁ?

Those that want to differ different anusvaras or anusvara and anunasika.

**Comment by kmadathil** [comment]
Can you request that [indic_transliteration](https://github.com/sanskrit-coders/indic_transliteration) support this encoding? Our support will come automatically.

**Comment by kmadathil** [comment]
We have two options
  1) Handle this under "normalize" if it is indeed a common use-case
  2) Get an ISO15919 scheme implemented, where this is legal

**Comment by gasyoun** [comment]
> We have two options

Anyway will do.

**Comment by kmadathil** [comment]
Since Vishvas isn't too keen to implement it, this will happen as and when we have some extra bandwidth. In the meantime, please use IAST.

**Comment by kmadathil** [comment]
A temporary solution has been implemented, which internally forces ISO15919 to IAST. We will implement a full ISO15919 later.

**Comment by kmadathil** [comment]
Added UI support for this. Please remember to uncheck Strict Mode if you want to use ISO15919
![smb](https://user-images.githubusercontent.com/9718582/114617267-c7539500-9c5c-11eb-9f75-822b8c54a1a3.png)
