### ISSUE TITLE
Microsoft Visual C++ 14

### ISSUE THREAD

**Issue by gasyoun** [kmadathil/sanskrit_parser#167]
Why in https://github.com/kmadathil/sanskrit_parser#installation if I install on 
Windows nothing is said about the need of Microsoft Visual C++ 14.0? It's 18 **gigabytes**

```
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/ 
```

![image_2021_03_31T12_31_30_028Z](https://user-images.githubusercontent.com/80761/113144826-5e205a80-9236-11eb-9c98-799f3a8252bf.png)

**Comment by kmadathil** [comment]
gensim is a dependency for us. This is a gensim install issue - asking the gensim team would be best.

**Comment by avinashvarna** [comment]
If you don't want to install MSVC build tools, you can install gensim from this website:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

Please pay special attention to this step:
```
Use pip version 19.2 or newer to install the downloaded .whl files. This page is not a pip package index.

Many binaries depend on numpy+mkl and the current Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for Python 3, or the Microsoft Visual C++ 2008 Redistributable Package x64, x86, and SP1 for Python 2.7.

Install numpy+mkl before other packages that depend on it.
```

Then download and install the version of gensim that corresponds to your python version:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#gensim

**Comment by avinashvarna** [comment]
@gasyoun @artanat @ VladimirWI could you please tell me the exact command you used to try to install `gensim`/`sanskrit_parser` and the python version, windows version, etc. you used? I tried it just now on a windows system *without* visual studio build tools, and it worked for me with python 3.8. I want to understand the differences between our setups.
