### ISSUE TITLE
Gensim dependency

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#168]
As reported in #167  - the dependency on gensim is causing installation to be complex for some.

We should consider making this easier on the end-user.

One possible option is something like (in `lexical_scorer.py`)
```
try:
    import gensim  
    with_gensim = True                  
except ImportError:
   with_gensim = False
```
and later use this to check if it's loaded or not. If the scorer is called, and this isn't loaded, we output an error message stating that gensim wasn't properly installed, and default to a sentence length based score (smaller is better)

**Comment by gasyoun** [comment]
> we output an error message stating that gensim wasn't properly installed

And part of what code it is. `Gensim` equals to 18 gigabytes of shitty code, thanks.

**Comment by drdhaval2785** [comment]
I didnt know gensim was that bulky, but it worked well when I tried it last.

**Comment by gasyoun** [comment]
> gensim was that bulky

You can have it only as a part of a HUGE mega-library. It's a monster.

**Comment by kmadathil** [comment]
@gasyoun - Please be mindful of norms. I have deleted a comment with a word that is not normally considered printable.

**Comment by gasyoun** [comment]
@kmadathil please excuse me. I get nervous when I do not understand how the code actually works and what it requires without no hints.

**Comment by kmadathil** [comment]
We decided to document an alternative gensim installation method instead of doing this. The issue will be closed after it is added to README.

**Comment by gasyoun** [comment]
> The issue will be closed after it is added to README.

Thanks.

**Comment by avinashvarna** [comment]
Updated README with the instructions. Please check and close if sufficient.
