### ISSUE TITLE
CMD Mode Output to Text File

### ISSUE THREAD

**Issue by gasyoun** [kmadathil/sanskrit_parser#169]
![dsdadasdassda](https://user-images.githubusercontent.com/80761/113288307-74421f80-92f7-11eb-9009-c6a87792425d.png)

How to the results not only in CMD, but TXT?

![dasdasdasadsadsadsadsads](https://user-images.githubusercontent.com/80761/113288340-802de180-92f7-11eb-89b0-38945fd157cf.png)

Another issue. In vakya mode goes further. In sandhi mode stops.

**Comment by kmadathil** [comment]
Sorry, we cannot teach you how to use Windows.
