### ISSUE TITLE
Mahesvarasutras returns extra "a" with vyanjanas

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#17]
`$ python MaheshvaraSutras.py --pratyahara hal --varna a`
`aiuR fxk eoN EOc hayavaraw laR YamaNaRanam JaBaY GaQaDaz jabagaqadaS KaPaCaWaTacawatav kapay Sazasar hal`
`हल्`
`हयवरलञमङणनझभघढधजबगडदखफछठथचटतकपशषसह`
`Is अ in हल्?`
`True`

**Comment by drdhaval2785** [comment]
अकारः मुखसुखार्थः ।

**Comment by kmadathil** [comment]
Added an option to remove internal 'a's in getPratyahara. 

However, keeping them in makes search simpler for most cases except the 'a' varna. isInPratyahara treats the 'a' varna separately to handle this case. 

I think this should fix all cases. PLMK if this doesn't do the trick.

**Comment by kmadathil** [comment]
$ python MaheshvaraSutras.py --pratyahara ac --varna a
aiuR fxk eoN EOc hayavaraw laR YamaNaRanam JaBaY GaQaDaz jabagaqadaS KaPaCaWaTacawatav kapay Sazasar hal 
अच्
अइउऋऌएओऐऔ
Is अ in अच्?
True
$ python MaheshvaraSutras.py --pratyahara hal --varna a
aiuR fxk eoN EOc hayavaraw laR YamaNaRanam JaBaY GaQaDaz jabagaqadaS KaPaCaWaTacawatav kapay Sazasar hal 
हल्
हयवरलञमङणनझभघढधजबगडदखफछठथचटतकपशषसह
Is अ in हल्?
False
$ python MaheshvaraSutras.py --pratyahara hal --varna k
aiuR fxk eoN EOc hayavaraw laR YamaNaRanam JaBaY GaQaDaz jabagaqadaS KaPaCaWaTacawatav kapay Sazasar hal 
हल्
हयवरलञमङणनझभघढधजबगडदखफछठथचटतकपशषसह
Is क् in हल्?
True
$ python MaheshvaraSutras.py --pratyahara hal --varna ka
aiuR fxk eoN EOc hayavaraw laR YamaNaRanam JaBaY GaQaDaz jabagaqadaS KaPaCaWaTacawatav kapay Sazasar hal 
हल्
हयवरलञमङणनझभघढधजबगडदखफछठथचटतकपशषसह
Is क in हल्?
True

**Comment by avinashvarna** [comment]
I think this will work. Would you also mind adding an option to return the dIrghas of vowels in getpratyAhAra? It makes things work nicely if the caller does not have to keep running another regexp on the results to add all the dIrghas. E.g.
`if dirghas:`
`            ts = re.sub('[aiufx]+', lambda m: m.group(0) + m.group(0).upper(), ts)`
or something better if we want each of the hrasva/dIrgha pairs to be grouped together

**Comment by kmadathil** [comment]
I see the required code in your branch, and have added that into master.

**Comment by kmadathil** [comment]
Closing. Please reopen if issue is not resolved
