### ISSUE TITLE
ease up on sqalchemy requriements

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#177]
On my computer I get:

> sanskrit-parser 0.2.4 requires sqlalchemy<1.4, but you have sqlalchemy 1.4.37 which is incompatible.

Can you ease up on this version insistence?

**Comment by kmadathil** [comment]
@avinashvarna - Since this is your part of the code, is the reason to fix sqlalchemy at < 1.4 still valid?

**Comment by avinashvarna** [comment]
It originally comes from the sanskrit_util library [requirement](https://github.com/avinashvarna/sanskrit_util/blob/241647185b0ba3155280b3256e002d0343e088d2/setup.cfg#L19) that we rely on. My recollection is that travis was not resolving the dependencies properly and I had to replicate it here. I can remove it from here, but the fundamental problem remains.

sqlalchemy 1.4 made some changes that breaks the sanskrit_util library. Unfortunately, I don't have the expertise or bandwidth to figure out the issue. Maybe @codito can take a look if he has time?

**Comment by vvasuki** [comment]
From @akprasad at https://discord.com/channels/987203574947795004/987203574947795007/990782379960451132 , who is (happily for us) active again - 

> In the medium term Ambuda needs to have a high-quality Sanskrit parser. DCS data was great to bootstrap but it's difficult to run the DCS program as a web service, e.g., or to integrate it into the website.
>
> Some kind of unification makes sense, but I also worked on sanskrit when I was a much more junior engineer (almost 7 years ago!) and there are design decisions that I would much rather revisit rather than trying to fit programs into that mold. For example, I now think that it doesn't make sense for sanskrit to include sqlalchemy code at all. I'd like to read through sanskrit_util and see if there's a cleaner way forward without the burden of these legacy decisions. (I don't mean a complete rewrite, which would be a waste -- mainly, I mean some intentional refactoring to make the code lighter and more resilient.) 
>
> I'm writing up a plan for Ambuda's next three months, and revisiting+impoving some version of this package is part of what I want to achieve by the end of Q3.

**Comment by kmadathil** [comment]
Can we autodetect the sqlalchemy version and disable `sanskrit_utils` ?

**Comment by avinashvarna** [comment]
We could, but I am not in favor of it. Dependency management is a general problem, and the typical (industry-wide) solution has been to use virtual environments. If we start down this path, where do we draw the line? We would have to do this for every non-critical package, and then testing and validating that all these combinations work properly becomes complex.

We could just wait until this library is rewritten, or someone can invest time to figure out the problem. In the meantime, maybe we recommend our users to use a virtual environment, or online solutions such as binder/github codespaces.

**Comment by kmadathil** [comment]
I am in favour of a virtual environment if that works. @vvasuki - does your use case allow for that?

**Comment by vvasuki** [comment]
> We could, but I am not in favor of it. Dependency management is a general problem, and the typical (industry-wide) solution has been to use virtual environments. 

virtual environments don't solve the problem if one _needs_ multiple relevant packages within the same environment (which is the typical case). sanskrit_parser is far from the only package folks like me want to use!

I certainly haven't felt the need to work on different projects in different virtual environments on my personal computer so far (sounds complicated life!) - so, this problem is atypical in my experience, even if the "industry" found it typical enough to come up with silos (maybe they need to inevitably use less maintained/ legacy code for some projects?).

> If we start down this path, where do we draw the line? We would have to do this for every non-critical package, and then testing and validating that all these combinations work properly becomes complex.

Don't know if it's that bad - I didn't see any other such warning

> 
> We could just wait until this library is rewritten, or someone can invest time to figure out the problem. 

It's certainly not urgent.

> In the meantime, maybe we recommend our users to use a virtual environment, or online solutions such as binder/github codespaces.

I'm leery about whether people will take it seriously - may be good for serious contributors? (I for one, being a casual / curious user will just continue running in my default env).

**Comment by avinashvarna** [comment]
> virtual environments don't solve the problem if one needs multiple relevant packages within the same environment (which is the typical case). sanskrit_parser is far from the only package folks like me want to use!

Fair enough. If there are multiple packages with conflicting requirements, then virtual environments don't solve the problem on their own.

@kmadathil, your call. I am fine with making this change/delaying until the library gets rewritten. After all, even one person is probably a significant portion of our active users ;-) Hopefully, we don't run into too many such issues.

**Comment by akprasad** [comment]
I'm starting my rewrite / refactor of `sanskrit` now. Since that package is used here and since `sanskrit` is a generic name, I will probably rename the package to avoid too much confusion and to avoid breaking things.

Feel free to suggest a good name -- my mind went to `brahmi`, `bharati`, `bhasha`, `vak`, `vani`, ... basically just what's in the Amarakosha. Or perhaps something utilitarian like `satk` (sanskrit toolkit), etc.

**Comment by vvasuki** [comment]
@akprasad my sincere suggestion to you as well as sanskrit_parser authors is to separate out different functionalities in different packages - despite having dependencies. For example, in this case, there is no reason why transliteration module should coexist with sandhi module within the same package (also, there is already https://github.com/indic-transliteration/indic_transliteration_py ). Someone who wants to use or contribute to just transliteration should not need to install sandhi etc..

**Comment by akprasad** [comment]
> Someone who wants to use or contribute to just transliteration should not need to install sandhi etc..

Agreed -- I think I made `sanskrit` that way originally so it could be an all-in-one package before `indic_transliteration` was available.

**Comment by avinashvarna** [comment]
IMHO, a descriptive name (such as `indic_transliteration`) is easier to
remember than an abstract name.

**Comment by kmadathil** [comment]
The core functionalities of `sanskrit_parser` are the sandhi and vAkya (aka 'dependency parsing') analysis. 

All transliteration is from `indic_transliteration` (with a wrapper) - I don't think we have any actual added functionality over this. 

We use pada analysis ('morphological analysis' in modernese) from INRIA and the `sanskrit_utils` (which I believe is a clone of the `sanskrit` package), again with a wrapper. 

I also have a WIP pada (and later vakya) generator - which is waiting for some solid time from me - which I would ideally move to another package. 

Open to ideas on how we structure all this.

**Comment by vvasuki** [comment]
सन्धिघटनं भिन्नमञ्जूषायाम् भवितुम् अर्हति। सन्धिविघटनम् अस्त्व् अत्र नाम।

**Comment by kmadathil** [comment]
Possible path- we claim the `sanskrit` namespace, and use [namespace packages ](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#using-find-namespace-or-find-namespace-packages)

Thus, we can package up `sanskrit.sandhi` (as `sanskrit-sandhi` in pypi), `sanskrit.parser`  etc. separately.

**Comment by akprasad** [comment]
I believe https://github.com/avinashvarna/sanskrit_util/pull/2 will fix `sanskrit_util` to support sqlalchemy >1.4. I ran unit tests but didn't run any deeper integration tests, so please run other tests as you see fit.

@avinashvarna or @kmadathil : please let me know if you can take a look soon, as this is blocking some work on Ambuda.

**Comment by kmadathil** [comment]
I can see that Avinash has released `sanskrit_util`, but it seems to break `sanskrit_parser`. @avinashvarna - do we need to change anything in `sanskrit_parser` to match those changes?

**Comment by akprasad** [comment]
@kmadathil This looks like the issue I mentioned in my pull request:

> Null values are no longer allowed in polymorphic identities. So `Root` now has a `discriminator` value of 0 instead of null. Existing tables will need to be migrated.

The fix is to either rebuild the database or update your existing database to set the `discriminator` column to 0 where it is currently null.

**Comment by kmadathil** [comment]
Makes sense. @avinashvarna - Avinash, you have a script to rebuild this right? Can you run it when you have time?

**Comment by avinashvarna** [comment]
I'll try to do it this weekend. I don't know if the option that @akprasad suggested above to just replace `null` with `0` would be faster though.

**Comment by kmadathil** [comment]
I've updated `sanskrit_data.db` to replace null with 0 in `root.discriminator` and it seems to work.

**Comment by kmadathil** [comment]
Made release v0.2.5 with the manually updated db
