### ISSUE TITLE
Testing SanskritLexicalAnalyzer

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#19]
I have added a few manual tests for py.test (in the dag branch, pending merge to master).

How do we get more automated tests? Can we generate them from the DCS scraper output?

https://github.com/sanskrit-coders/dcs-scraper

**Comment by drdhaval2785** [comment]
Maybe the same set as @avarna is using from UoHyd.

**Comment by avinashvarna** [comment]
Yes, I agree with @drdhaval2785. We can start from the UoHyd dataset which is smaller and well-contained first. Once we have good results on that, we can migrate to DCS. I have some scripts for playing with both. Will try to add them this week

**Comment by kmadathil** [comment]
@avinashvarna 
Thanks. Will wait for your scripts

**Comment by kmadathil** [comment]
@avinashvarna Thanks. I've merged this into dag-nx and will start to use this. I will keep this open until tests pass.

**Comment by kmadathil** [comment]
Began testing with uohd data. Looking through the failures shows that uohd data doesn't split upasargas or samAsa, while we do.

**Comment by kmadathil** [comment]
@drdhaval2785 @avinashvarna 
I'm planning to try to get UoHD tests to pass using this approach
  1) Directly check our output against UoHD split. If the latter is not in the former
  2) For each word in UoHD split, check if it is in the INRIA db. If it is not, replace with the first split we get by splitting it.
  3) Check if the output of 2 is in our split in step 1

Please comment.

**Comment by avinashvarna** [comment]
I think it's a reasonable start in the absence of a better db, but I am a bit concerned about using the splitter to test the splitter in the long run. If we are planning to figure out a better solution for the long term (the Level 1 solution referred to in the README), then this might be OK as a first step, and we modify it as we develop our level 1 solution.

**Comment by kmadathil** [comment]
Level 1 is needed in the longer term. 
I share your concern - there is a definite possibility that this can hide errors in splits.

**Comment by kmadathil** [comment]
Closing this
