### ISSUE TITLE
DAG generation code creates duplicate nodes

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#21]
I merged the dag-nx changes into my sandhi branch and while testing, discovered that the DAG generation code is creating duplicate nodes. E.g.
$ python SanskritLexicalAnalyzer.py --split astyuttarasyAmdiSi --input-encoding SLP1
Parsing of XMLs started at 2017-07-11 23:51:34.063000
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-11 23:51:39.569000
Input String: astyuttarasyAmdiSi
Input String in SLP1: astyuttarasyAmdiSi
Start Split: 2017-07-11 23:51:46.504000
End DAG generation: 2017-07-11 23:51:46.520000
End pathfinding: 2017-07-11 23:51:46.524000
Found 10 splits
[[u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttarasyAm', u'diSi']]
and all the paths are really the same.

I think it is the following portion of the code in _possible_splits:
`if rdag:`
`                            # Make sure we got a graph back`
`                            assert isinstance(rdag,SanskritLexicalGraph)`
`                            # if there are valid splits of the right side`
`                            # Extend splits list with s_c_left appended with possible splits of s_c_right`
`                            t = SanskritLexicalGraph(s_c_left,end=False)`
The last line will create a new object with the same s_c_left, even if multiple splits have the same left. It is well past midnight my time, so will try to follow it up tomorrow.

Can be reproduced by running the avinashvarna branch with the above inputs. Will write out the graph structure to a graphviz dot file (requires pydotplus) which clearly shows the duplicate nodes. (I've also checked in the .dot file as a sample)

**Comment by kmadathil** [comment]
(dag-nx)*$ python SanskritLexicalAnalyzer.py --split astyuttarasyAmdiSi --input-encoding SLP1
Parsing of XMLs started at 2017-07-12 13:23:27.473790
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-12 13:23:32.423183
Input String: astyuttarasyAmdiSi
Input String in SLP1: astyuttarasyAmdiSi
Start Split: 2017-07-12 13:23:34.681279
End DAG generation: 2017-07-12 13:23:34.688061
End pathfinding: 2017-07-12 13:23:34.693550
[[u'asti', u'uttarasyAm', u'diSi'], [u'asti', u'uttas', u'rasyAm', u'diSi'], [u'asti', u'uttara', u'syAm', u'diSi'], [u'asti', u'ut', u'tara', u'syAm', u'diSi']]

Not seen in dag-nx. I will look at your branch.

**Comment by kmadathil** [comment]
But, you're right that that code creates unnecessary nodes. I will fix that part, but that should not create multiple instances of the same paths.

**Comment by kmadathil** [comment]
Once I integrate sandhi.py, I see the following

[u'asti', u'uttarasyAmdiSi'] returned twice here in splits

1) 
Sandhi: splitting: astyuttarasyAmdiSi at t (2)
s_c_list: [[u'as', u'tyuttarasyAmdiSi'], [u'aH', u'tyuttarasyAmdiSi'], [u'ast', u'yuttarasyAmdiSi'], [u'ast', u'yuttarasyAmdiSi'], [u'asti', u'uttarasyAmdiSi'], [u'astI', u'uttarasyA\
mdiSi']

And once here
2) Sandhi: splitting: astyuttarasyAmdiSi at y (3)
s_c_list: [[u'asti', u'uttarasyAmdiSi'], [u'astI', u'uttarasyAmdiSi'], [u'asty', u'uttarasyAmdiSi']]

For a total of three redundant returns of the same split.

Looks like this is being very aggressive in returning splits!

**Comment by avinashvarna** [comment]
This is partly because I had added rules like #  उदः स्थास्तम्भोः पूर्वस्य ८.४.६१ + झरो झरि सवर्णे (८.४.६५) to handle special cases, and it was causing the splitter to consider extra long right contexts. For this, maybe I can just remove the special cases.

The other reason is more fundamental to architecture of the sandhi object (specifically the pre-expansion). Since it automatically figures out the backward splits from forward splits, and pre-expands them, it has to consider all possible left and right contexts. I will have to think a little bit more about how to fix this without breaking other cases.

**Comment by kmadathil** [comment]
@avinashvarna : Two simple checks to add to your tests
  1) Do not return the same split twice in the same position
  2) Do not return the same split from different positions

**Comment by avinashvarna** [comment]
That's a good suggestion. Thanks. Will add it to the tests.

**Comment by avinashvarna** [comment]
Doing 1 was reasonably straightforward, but doing 2 looked like it might require some modifications to the way we've been writing rules so far. Instead, I think there is an alternate solution by moving the iteration of splitting the input into the sandhi module, and returning a **set** of splits. This automatically solves the duplication problem (and IMHO has the side benefit of making the code simpler as there is one less nesting of the for loop). I don't think it adds any additional time complexity, because we were already looping over splitting at each position. We just do it at once now, meaning we need to store a few extra strings.

I made these corresponding changes for the internal splitter as well on my branch, and tested everything using the existing tests to ensure nothing was broken.

@kmadathil if you think these changes are reasonable, please merge them into master, so that we can use them going forward.

**Comment by kmadathil** [comment]
Absolutely.
I have created an integ branch for this purpose. Let's maintain that as an intermediate stage for integration work before master. Please feel free to merge into and push this branch directly if you need, so you can have other work in your branch. The intent is that it stages short lived merge experiments.
I am also merging integ into master since the results are good.
I am switching the default to use the sandhi.py module. There is now a --use-internal-sandhi-splitter option to SanskritLexicalAnalyzer.py
