### ISSUE TITLE
Wrong split for SrIrapi

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#23]
Sandhi module

(integ)*$ python SanskritLexicalAnalyzer.py --split SrIrapi --input-encoding SLP1 
Parsing of XMLs started at 2017-07-16 11:50:23.374043
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-16 11:50:28.310012
Input String: SrIrapi
Input String in SLP1: SrIrapi
Start Split: 2017-07-16 11:50:34.029952
End DAG generation: 2017-07-16 11:50:34.032363
End pathfinding: 2017-07-16 11:50:34.033762
Splits:
[u'Sri', u'Ira', u'pi']
[u'SrI', u'Ira', u'pi']

Internal splitter:

(integ)*$ python SanskritLexicalAnalyzer.py --split SrIrapi --input-encoding SLP1  --use-internal-sandhi-splitter
Parsing of XMLs started at 2017-07-16 11:50:45.124203
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-16 11:50:50.126418
Input String: SrIrapi
Input String in SLP1: SrIrapi
Start Split: 2017-07-16 11:50:55.797431
End DAG generation: 2017-07-16 11:50:55.799320
End pathfinding: 2017-07-16 11:50:55.803311
Splits:
[u'SrIs', u'api']
[u'SrI', u'ras', u'pi']
[u'Sri', u'Iras', u'pi']
[u'SrI', u'Iras', u'pi']
[u'Sri', u'Ira', u'pi']
[u'SrI', u'iras', u'pi']
[u'Sri', u'iras', u'pi']
[u'SrI', u'Ira', u'pi']

**Comment by avinashvarna** [comment]
I don't see it on my branch:
 (avinashvarna) $ python SanskritLexicalAnalyzer.py --split --input-encoding SLP1 --max-paths 25 SrIrapi
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-16 10:21:37.869000
Input String: SrIrapi
Input String in SLP1: SrIrapi
Start Split: 2017-07-16 10:21:43.024000
End DAG generation: 2017-07-16 10:21:43.027000
End pathfinding: 2017-07-16 10:21:43.038000
Splits:
[u'SrIs', u'api']
[u'SrI', u'Ira', u'pi']
[u'Sri', u'Ira', u'pi']
[u'SrI', u'Iras', u'pi']
[u'Sri', u'Iras', u'pi']
[u'SrI', u'iras', u'pi']
[u'Sri', u'iras', u'pi']
[u'SrI', u'ras', u'pi']

Same for #24. Will take a look at the integ branch.

**Comment by avinashvarna** [comment]
My apologies, looks like the internal splitter was the default on my branch. This has to do with the issue we discussed about accepting visarga for the forward sandhi but returning s for the backward split. I had forgotten to write the rule to take this into account. I updated it, and it seems to be working. Will test it and check it in

**Comment by avinashvarna** [comment]
Please check if it is fixed now.
