### ISSUE TITLE
शश्छोऽटि - ८.४.६३

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#27]
Interaction with scunA scu is not correctly implemented. Perhaps a fix like you did for  झयो होऽन्यतरस्याम्
where the interaction is captured as well is called for? 

(integ)*$ python SanskritLexicalAnalyzer.py --split --input-encoding SLP1 'visfjecCivam'
Parsing of XMLs started at 2017-07-27 12:51:51.187147
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-27 12:51:56.268704
Input String: visfjecCivam

Input String in SLP1: visfjecCivam

Start Split: 2017-07-27 12:52:02.085158
End DAG generation: 2017-07-27 12:52:02.090917
No Valid Splits Found

**Comment by avinashvarna** [comment]
$ python SanskritLexicalAnalyzer.py --split --input-encoding SLP1 'visfjecCivam'
Parsing of XMLs started at 2017-07-30 17:48:48.425000
Parsed data exists and is newer than all XML files. Loading file
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-30 17:48:50.764000
Input String: visfjecCivam
Input String in SLP1: visfjecCivam
Start Split: 2017-07-30 17:48:54.575000
End DAG generation: 2017-07-30 17:48:54.582000
End pathfinding: 2017-07-30 17:48:54.583000
Splits:
[u'vi', u'sfjet', u'Sivam']
[u'vi', u'sfje', u'at', u'Sivam']

@kmadathil please verify and close

**Comment by kmadathil** [comment]
Closing.
