### ISSUE TITLE
Reorganize code, publish on pip

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#29]
put everything in a sanskrit_parser module. Then follow https://github.com/sanskrit-coders/indic_transliteration template to publish to pip. I can do the needful if this sounds good..

Utility: This will let others start using your work.

**Comment by kmadathil** [comment]
Sounds good.

@avinashvarna : Please look at the integ branch. I have made the necessary code and organization changes. If I have not broken any of your stuff (py.test test_sandhi.py does work), we can promote this to master.

**Comment by kmadathil** [comment]
@avinashvarna : I've also moved all tests to a top level tests directory. Please check.
@vvasuki : Please check if the packaging files and directory structure are as per your recommendation.

**Comment by vvasuki** [comment]
Looks good! https://pypi.python.org/pypi?%3Aaction=list_classifiers does not include     'Natural Language :: Sanskrit', - please remove from setup.py . 
* I am unclear about the xmlwrapper part - do you need to include http://sanskrit.rocq.inria.fr/DATA/XML in your package for it to work? Is it ready to be installed and used as a pip module?
* The most important piece missing - better README.md. Besides command-line invocations, please include example function calls (even to the xmlwrapper rewrite) and add installation instructions (as in https://github.com/sanskrit-coders/indic_transliteration ). It's ok if the README slightly lags the actual available facilities in the code - it's a good idea to make it as convenient as possible for users/ testers.

**Comment by avinashvarna** [comment]
Nothing is broken as far as I can see. The test indeed runs and finishes. I ran the sandhi file from the command prompt and that worked as well. Feel free to promote to master when you are ready.
Reassigning to @kmadathil

**Comment by kmadathil** [comment]
@vvasuki 
I've removed the  'Natural Language :: Sanskrit'
I've also modified the author details thus:
```
  author='Sanskrit programmers',
  author_email='sanskrit-programmers@googlegroups.com',
```
Hope that's fine. The intent is to signal that this is a group project. 

As of now, we're dependent on https://github.com/drdhaval2785/inriaxmlwrapper being installed independently. It is not ready for pip yet.

**Comment by vvasuki** [comment]
Regarding email address - definitely fine - good advertisement for the group as well. Your readme would ideally point to the issues page, which will suffice to receive communication from users.

I've already instigated 1 with https://github.com/drdhaval2785/inriaxmlwrapper/issues/9 . Unless @drdhaval2785 can attend to it now (unlikely), you should temporarily go ahead with 2 - since you've contributed there I'm assuming it should not be too much of a burden.

**Comment by avinashvarna** [comment]
2. would definitely help with making the package standalone and easier to install.  While I am not a fan of duplicating code, we only use a small portion of inriaxmlwrapper, so we could just include it in here. I can update the code that I was planning to check-in to inriaxmlwrapper to also download the files if necessary and add it to this project. I will add it on integ and let's see how it goes.

**Comment by kmadathil** [comment]
Yes, that'd be best for now!

**Comment by drdhaval2785** [comment]
Yes. Only a small portion of code was used here. Better to copy that portion and include the data files in this repo.

In case there are some optimizations in inriaxmlwrapper, I will notify.

**Comment by avinashvarna** [comment]
Pushed initial implementation. Please see integ branch 55d5971

**Comment by kmadathil** [comment]
Shouldn't we ship the XML files instead of downloading them in the code?

**Comment by drdhaval2785** [comment]
To minimize on bandwidth and time, better to download from sanskrit.inria.fr site and untar locally during installation process. That will ensure that latest version of data is associated

**Comment by avinashvarna** [comment]
We could, if we wanted to ensure strict versioning of the XML files and
installs be strictly reproducible. However that means that the data needs
to be replicated in multiple repos. Ideally I would like to point it to the
inria git repository which should be the single source of the data.

I have seen several packages that deal with large datasets (e.g. nltk) just
download the datasets when necessary.

If we wanted to ship the files, we can just check in the files the code
downloads and it will automatically use them the next time the class is
instantiated. The code doesn't need to change.

**Comment by kmadathil** [comment]
I've integrated into SanskritLexicalAnalyzer.py. Things seem to work fine. 
Now to fix the README and we should be good to go

**Comment by avinashvarna** [comment]
I've updated the README with a lot of usage examples.
@vvasuki Is this along the lines of what you had in mind?

**Comment by vvasuki** [comment]
@avinashvarna Indeed so! Except, I'd put the most interesting things at the top.

यद्यपि README.md परिष्कारमेवामन्ये मार्गं ग्राह्यम् सूत्रोद्घाटनसमये, न तथाधुना। सर्वदैव टिप्पणयो यान्त्रान्त्रस्थाः स्युः - अन्यता यन्त्र-टिप्पण्योर् भेदो जायेत वर्धेत च। तदर्थम् अस्ति सरलो मार्गः कश्चन, किञ्च तद्विषये सूत्रान्तरम् प्रारभिष्ये।

**Comment by kmadathil** [comment]
README.md इत्यस्य पुनर्विधानं कृतं मया विश्वासस्य टिप्पण्यानुसृतं "lexical analysis, inriawrapper above pratyahara above transliteration" इति  प्रकारेण |   दृश्यतामिदं [सङ्केतेन](https://github.com/kmadathil/sanskrit_parser/blob/2c033bf/README.md)

**Comment by vvasuki** [comment]
शोभनतरम् अलङ्कृतम् 🙏। स्थापनबाधाश् चेन् निवारिताः, परीक्षै कृत्यं युष्मदीयम्। ततश्च सूत्रस्यास्य पिधानम्।

**Comment by avinashvarna** [comment]
मया तु सोपानक्रमेण tutorial-रूपेण विवरणम् अलेखि । एतदपि युज्यते । क्रमपरिवर्तनेन प्रथमम् उदाहरणे जायमानः क्लेशः (sentence variable नास्तीत्ययम्) परिहृतश्च । समीक्ष्य master प्रति प्रेष्यताम् !

**Comment by kmadathil** [comment]
PyPI इत्यस्मिन् स्थापितं sanskrit_parser यस्मात् `pip install sanskrit_parser` इत्यनेन अवस्थापितुं‌ शक्यते सङ्गणके अधुना  | तदनुरूपं README.md इत्यस्य परिणतिः कृता,  master शाखायां integ शाखायाः‌ समवायोपि कृतः  |

एकवारं तस्य अवस्थापनस्य उपयोगस्य च परीक्षणं क्रियतां |‌ तत्पश्चात् पिधानम् करिष्यामोस्य विषयस्य |

**Comment by avinashvarna** [comment]
बाढम् ! अत्रापि अन्विष्टं मया - https://pypi.python.org/pypi/sanskrit-parser । अनिर्वचनीयः कश्चन आनन्दोऽनुभूयते ! :) 

sanskrit programmers गणेऽप्यस्य घोषणा क्रियताम् । #32 इत्यादिषु कार्येषु साहाय्यं प्राप्यते चेत् शीघ्रतरेण गत्या कार्यम् अग्रे साधयिष्यामः !

**Comment by avinashvarna** [comment]
Pypi https://pypi.python.org/pypi/sanskrit-parser मध्ये तु `pip install git+https://github.com/kmadathil/sanskrit_parser/` दृश्यते नु ?
प्रथमोदाहरणे कृतः परिष्कारोऽपि न सन्दृश्यते ?

**Comment by kmadathil** [comment]
शोधीकृतं, इदानीं पश्यतु

**Comment by kmadathil** [comment]
पिधानम्

**Comment by vvasuki** [comment]
सु॒कृ॒तम् बान्धवौ! किञ्च, `pip2 install git+https://github.com/kmadathil/sanskrit_parser/ -U` इत्यपि प्रकाशनमार्गो देयः - येन भूरिशः परिवर्तमानस्यास्य तन्त्रांशस्य नूतनतमप्रतिं प्राप्तुं स्यात् सौलभ्यम् (यथा [कृतमत्र](https://github.com/sanskrit-coders/sanskrit_data#installation))।
