### ISSUE TITLE
Separate out self-contained modules for reuse

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#3]
-- From vvasuki

Something to keep in mind - ​Something we learned from past experience is that it is best to separate​ out self contained modules and publish them in pip (which is very simple - you've got the indic transliteration module as an example). This will encourage reuse like nothing else.

**Comment by avinashvarna** [comment]
@vvasuki Do you think the pip package with the sandhi/lexical_analyzer/morphological_analyzer/util sub-modules addresses the comments? If so, can we close this issue?

**Comment by vvasuki** [comment]
I'd said that encouraging smaller pip packages (someone might need tagging but not sandhi stuff). So far sanskrit_parser is mostly:

* tagging
* sandhi making and breaking.

I don't think it's worth the effort to separate out tagging into a separate pip package. I think we can close this bug while remembering this in the future when we see more functionailty being crammed into the same package.
