### ISSUE TITLE
Better L1 candidate/reuse ?

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#30]
Came across this project which seems to have identical goals - https://github.com/sanskrit/sanskrit. (Hasn't been updated in 2 years though. I seem to recall the author saying on the sanskrit-programmers list that he has moved on to meditation, etc.)

Still going through the code, but it seems to have features such as trying to see if a stem in the db could have produced the given word by looking at the sup form, etc. We could test it to see if it recognizes more forms compared to the INRIA db, since it combines words from MW, INRIA and Learnsanskrit.org db.

**Comment by kmadathil** [comment]
Good! Let me dig into this as well.

**Comment by kmadathil** [comment]
We should create a module shell for L1 in any case, so we can switch between different such L1 implementations, and later roll out our own without affecting any of the other modules much.

**Comment by avinashvarna** [comment]
ह्यः रात्रौ मया एतत् कीञ्चित् परिशीलितम् । उत्तमः तन्त्रांशो वर्तते । अतीवलाघवेन अधिकानि रूपाणि अभिज्ञायन्ते । एतत् INRIA xml इत्येतदपि input रूपेण स्वीकरोति । अतः तस्यापि superset वर्तते । यदि अन्येन केनापि एतस्य परिशीलनं क्रियमाणम् अस्ति तर्हि कृपया सूचयतु । नो चेत् अहम् अस्मिन् सप्ताहान्ते एतानि कार्याणि कर्तुम् इच्छामि -
- Define a common interface for word tag lookup (as also suggested by @kmadathil)
- Update current InriaXMLWrapper to implement this interface
- Implement a wrapper around the analyze class in https://github.com/sanskrit/sanskrit that implements the same interface to allow us to seamlessly switch from one to the other
- Long term - implement a common schema for the returned tags along the lines of https://github.com/sanskrit-coders/sanskrit_data and have all these classes return the results following the common schema

भवतां विचारान् सूचयन्तु ।

**Comment by kmadathil** [comment]
उत्तमम् |‌ morpho शखायां मया एकं inriaxmltagmapper इति निर्मितमस्ति, तदपि दृश्यतां | तेन INRIA-याः‌ tags विवर्तन्ते अस्माभिः पठितव्यरूपेषु | तस्यापि यथायुक्तं विस्तारो भवितुमर्हति

**Comment by avinashvarna** [comment]
I have started the integration. For now, combining both the databases seems to give better results. In fact the top results are pretty good.
$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer astyuttarasyAMdishidevatAtmAhimAlayonAmanagAdhirAjaH --split --lexical-lookup combined
Splits:
[u'asti', u'uttarasyAm', u'diSi', u'devatAtmAs', u'himAlayas', u'anAma', u'nagADirAjas']
[u'astI', u'uttarasyAm', u'diSi', u'devatAtmAs', u'himAlayas', u'anAma', u'nagADirAjas']
[u'asti', u'uttarasyAm', u'diSi', u'devatAtmA', u'himAlayas', u'anAma', u'nagADirAjas']
[u'asti', u'uttarasyAm', u'diSi', u'devatAtmAs', u'himAlayas', u'nAma', u'nagADirAjas']
[u'astI', u'uttarasyAm', u'diSi', u'devatAtmA', u'himAlayas', u'anAma', u'nagADirAjas']
[u'astI', u'uttarasyAm', u'diSi', u'devatAtmAs', u'himAlayas', u'nAma', u'nagADirAjas']
**[u'asti', u'uttarasyAm', u'diSi', u'devatAtmA', u'himAlayas', u'nAma', u'nagADirAjas']**
[u'astI', u'uttarasyAm', u'diSi', u'devatAtmA', u'himAlayas', u'nAma', u'nagADirAjas']
[u'asti', u'uttaras', u'yAm', u'diSi', u'devatAtmAs', u'himAlayas', u'anAma', u'nagADirAjas']
[u'asti', u'uttarasyAm', u'di', u'Si', u'devatAtmAs', u'himAlayas', u'anAma', u'nagADirAjas']

$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer pUrvAparOtoyaniDIvagAhyasTitaHpfTivyAivamAnadaRqaH --split --lexical-lookup combined
Input String: pUrvAparOtoyaniDIvagAhyasTitaHpfTivyAivamAnadaRqaH
Input String in SLP1: pUrvAparOtoyaniDIvagAhyasTitaHpfTivyAivamAnadaRqaH
Start Split: 2017-08-04 01:12:37.960000
End DAG generation: 2017-08-04 01:12:44.496000
End pathfinding: 2017-08-04 01:12:44.509000
Splits:
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyO', u'iva', u'mAnadam', u'qas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyAs', u'i', u'vamAn', u'adaRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyO', u'i', u'vamAn', u'adaRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyO', u'iva', u'mAn', u'adaRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyA', u'iva', u'mAn', u'adaRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyAs', u'iva', u'mAnadam', u'qas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyO', u'iva', u'mAna', u'daRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyE', u'i', u'vamAn', u'adaRqas']
[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyA', u'i', u'vamAn', u'adaRqas']
**[u'pUrvAparO', u'toyaniDI', u'vagAhya', u'sTitas', u'pfTivyA', u'iva', u'mAna', u'daRqas']**

I will clean up my code and check it in soon

**Comment by kmadathil** [comment]
How's this going, @avinashvarna  - if it's in any possible shape, could you commit to your branch (or a separate branch if you wish)?

**Comment by avinashvarna** [comment]
Sorry. I've been meaning to implement the tag mapper so that it would also work with the morphological analyzer that you've developed, but haven't had the time in the last couple of weeks. I will push the current state to my branch, so that others can develop it if they have a chance, or at least test out and find any bugs.

**Comment by avinashvarna** [comment]
Pushed in changes. Needs https://github.com/avinashvarna/sanskrit_lib to be on the PYTHONPATH (and yes, @vvasuki this should be published on pip as well. If Arun does not do it, I can do it later)

Example usage is shown in comment above:
```shell
python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer astyuttarasyAMdishidevatAtmAhimAlayonAmanagAdhirAjaH --split --lexical-lookup combined
python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer pUrvAparOtoyaniDIvagAhyasTitaHpfTivyAivamAnadaRqaH --split --lexical-lookup combined
```
The new argument --lexical-lookup can be one of inria / sanskrit_data / combined.

The sanskrit_data library can actually include all the forms of the inria db as well. It needs to be updated to parse the new files. So that's in the TODO list as well.

**Comment by vvasuki** [comment]
@avinashvarna - प्रकाशय मित्र। @akprasad न करिष्यति विषयान्तरे व्यस्तः।

**Comment by akprasad** [comment]
Best of luck! I ran into numerous data problems and hope you can avoid them.

In case it is useful, I also have a repo with cleaned-up data from multiple sources, including the Monier-Williams dictionary:

https://github.com/sanskrit/data

**Comment by avinashvarna** [comment]
I added a basic tag mapper and merged with "integ" branch to test the morphological analyzer. It appears to work properly. However, since the sanskrit data repo contains the entire MW dictionary, the number of words is much larger, and the number of valid morphological splits becomes huge. You can try 
```shell
python SanskritMorphologicalAnalyzer.py sAnugacCati --lexical-lookup combined
```
to get a taste. Some of it is due to duplication between the INRIA db and the sanskrit data repo, but the number of possibilities is still quite large. We could explore adding more constraints, or think of an alternate route.

**Comment by kmadathil** [comment]
Thanks. I was out for a few days thanks to travel - I will take a look at this and comment.

**Comment by avinashvarna** [comment]
I published https://github.com/avinashvarna/sanskrit_lib on pypi as [sanskrit_util](https://pypi.python.org/pypi/sanskrit-util) and integrated it into the sanskrit_util branch. It does help with improving the results for long sentences, as shown below. Please take a look at this branch and let me know if you have any comments/issues

![image](https://user-images.githubusercontent.com/758539/33522762-7564f072-d7b1-11e7-8c2f-370d382ac45a.png)
(I took the liberty of uploading a snapshot of the UI so that everyone can take a look at it :))

**Comment by kmadathil** [comment]
Nice. This would be a good time to also let @vvasuki and @codito  know about the UI that's being pulled up. Under the utils directory, we have a simple REST API (rest_api.py) wrapper coded with flask-restful. Once we're happy with this, we can serve this through nginx/apache, say from an aws machine, and allow folks to test this out using the UI and submit feedback

**Comment by kmadathil** [comment]
The splits look better. What's the default, using the INRIA tags or sanskrit_util or both? How come we don't also get hima + Alaya, naga+ aDirAja etc.?

**Comment by vvasuki** [comment]
Great! Excited to see the UI snapshot! 
- What does the JSON look like?
- Do you have a server to deploy it in, or would you like to let me put it on api.vedavaapi.org?
- Why not merge rest_api.py into the master branch?

**Comment by kmadathil** [comment]
It's on master already. 
cd util && python rest_api.py
http://localhost:5000/index.html

Toggle the raw json button to see the JSON. I recollect you had a JSON class? We might want to move that discussion to its own issue.

**Comment by avinashvarna** [comment]
@kmadathil - The default right now on the sanskrit_util branch is to use both INRIA and sanskrit_util, which is why you will see a lot of duplication in tags, and too many valid morphologies. 

We will also get hima + Alaya etc. if we increase the number of paths. The default in the lexical analyzer is to find the 10 *shortest* paths, and the splits containing hima + Alaya etc will be longer. The remaining 8 out of the 10 paths returned by the lexical analyzer were removed by the morphological analyzer as not having valid morphologies. We could increase the number of paths, but it already takes several minutes to analyze something this long.

@vvasuki - I am in the process of documenting the API using swagger editor. Right now the JSON is pretty simple.  As @kmadathil mentioned, we can move that discussion to a separate issue. It would be good to host on vedavaapi, if possible.

**Comment by vvasuki** [comment]
Ah - found the flask api. From past experience, I think that it is ideal for the flask API to be in a separate repository from this python package. Not only would changes be more manageable then, one should not need to replicate something available in pip just to run a REST api server. Do you agree? If so, I can create a new repo and work on deploying it.

**Comment by vvasuki** [comment]
Opened https://github.com/kmadathil/sanskrit_parser/issues/60 regarding swagger.

Also, the UI should be totally separate from the API - and should be static js / html (possibly using whatever framework you like - like angular, polymer etc..). Do not assume that the UI need by served by the flask server.

**Comment by avinashvarna** [comment]
Closing as the sanskrit data project has been integrated into master
