### ISSUE TITLE
python docs + sphynx + readthedocs.io + github pages

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#32]
https://github.com/kmadathil/sanskrit_parser/issues/29#issuecomment-319205485  इत्यनेन प्रेरितमिदम्।

सर्वदैव टिप्पणयो यान्त्रान्त्रस्थाः स्युः - अन्यता यन्त्र-टिप्पण्योर् भेदो जायेत वर्धेत च। तदर्थम् अस्ति सरलो मार्गः कश्चन। 

- python docstring-इत्येतेषाम् स्थापनम्। विशिष्य, https://github.com/kmadathil/sanskrit_parser/blob/integ/README.md इत्यत्र ये सूचनाः दत्ताः, ताः तत्तद्यन्त्रादेशान्त्रभागेषु सन्निविष्टाः स्युः। 
- ततः sphynx-यन्त्रस्योपयोगेन विवरण-पत्त्र-जननम्। https://docs.readthedocs.io/en/latest/getting_started.html#in-rst इति तत्परिचयो दत्तः।
- ततः readthedocs.io इत्यस्य https://github.com/kmadathil/sanskrit_parser इत्यनेन सम्पर्कस्य स्थापनम्।
- तथा विकल्पेन github pages इत्यस्य व्यवस्था, येन  readthedocs.io इत्यस्याभावे शक्नुयाम टिप्पणिप्रकाशनम् साधयितुम्। 

ऊर्ध्वं प्रथम सोपानम् साधयत। ततः सोपानान्तरारोहणे निर्विघ्नतासिद्ध्यर्थं स्वसम्पादितानुभव उपकुर्यात्।

**Comment by kmadathil** [comment]
दृष्टवानहमेतानि पृष्ठानि |‌ संशय एको वर्तते यत्  sphinx इत्यनेन कथं‌ README.md इत्यस्य निर्माणं शक्यम्?‌ 

उपयोगसूचनाः यदि docstrings मध्ये स्थापयेम वयं तर्हि तानि html मध्ये स्थापयति sphinx, न तु README.md इत्यस्मिन् ननु?‌ तर्हि html पृष्ठानां‌ यान्त्रिकनिर्माणं‌ कृत्वा README इत्यस्य निर्माणं‌ manually कुर्याम किम् ?‌

**Comment by avinashvarna** [comment]
README manually लेखनीयम् इति भासते । परन्तु तत्र सारांशः पर्याप्तप्रायः ।
उदाहरणार्थम् - https://github.com/networkx/networkx/tree/v1.11

**Comment by vvasuki** [comment]
आम्। README इत्यत्राधिका न भविष्यन्ति प्रयोगसूचनाः, यथा-  https://github.com/cloudant/python-cloudant#api-reference

**Comment by vvasuki** [comment]
html जनने वयं module-क्रमादिकम् निश्चेतुञ्च यथोचितसूचनान्तरनिवेशनञ्च व्यवस्थापयितुं शक्ष्यामः।

**Comment by kmadathil** [comment]
एवमेव कुर्याम |  उपयोगसूचनाः‌ तन्त्रांशमध्ये स्थापयित्वा index.rst इत्यस्मिन् सङ्केतरूपेण युञ्ज्मः | "sanskrit parser stack"  विषये सविस्तारं लिखितमपि अन्यत्र .rst सञ्चयिकायां स्थापनीयम्
 
README इत्यस्मिन् न्यूनतमाः सुचना एवाविष्यन्ते तत्पश्चात् |

**Comment by vvasuki** [comment]
[नानाविधप्रयोगैर्](https://sanskrit-coders.github.io/sanskrit_data/build/html/sanskrit_data_schema.html) लब्धानुभवशक्तिरहं संवृत्तः। तदनुसारम् अत्रापि लाघवेन सूचनासङ्कलनम् शक्यम्। https://pandoc.org/try/ इत्यनेन यथापेक्षं प्रयोगसूचनास्थानपरिवर्तनम् अधुना कार्यम्।

**Comment by kmadathil** [comment]
उत्तमम्! यदि अल्पायासेन अस्माकं‌ सूचनापुनर्व्यवधानं कर्तुं शक्यं त्वया तर्हि बहुकृथार्थोहम् !

**Comment by avinashvarna** [comment]
सत्यमेव अतिशोभनं वर्तते ! एतस्यापि तन्त्रांशस्य क्रमशो रचयेम ।

**Comment by vvasuki** [comment]
http://sanskrit-parser.readthedocs.io/en/latest/  इति प्रारम्भिकं किमपि जनितम्।  किन्तु, "This repository doesn't have a valid webhook set up, commits won't trigger new builds for this project. 
See your project integrations for more information." इति https://readthedocs.org/dashboard/sanskrit-parser/ इत्यत्र दृश्यते। काचिदधिकारसमस्या स्यात्।  @kmadathil  महाशयः  readthedocsलेखां सृष्ट्वा परिहरतु।

**Comment by vvasuki** [comment]
![image](https://user-images.githubusercontent.com/2664797/33519995-e49ef186-d766-11e7-840c-71a08abccb96.png)
 अत्र कार्त्तिकेयो योजनीयः। किञ्च तल्लेखानाम न ज्ञातम्।

**Comment by kmadathil** [comment]
readthedocs इत्यत्र मम account नासीत् | इदानीम् निर्मितम् kmadathil इति । माम्  maintainers इत्यत्र योजयतु | मया आत्मानं‌ योजयितुं न शक्यम् ।

**Comment by vvasuki** [comment]
तथा कृतम्। https://github.com/kmadathil/sanskrit_parser/issues/32#issuecomment-346941788 इत्येतत् परिहरणीयमधुना

**Comment by avinashvarna** [comment]
किम् एतत् परिहृतम् ? तथा चेत् एतत् "close" कर्तुं / पिधातुं शक्नुमः ।

**Comment by kmadathil** [comment]
आं परिहृतं मन्ये

**Comment by kmadathil** [comment]
अपि पिधामहे?‌ @vvasuki

**Comment by vvasuki** [comment]
आम्
