### ISSUE TITLE
सहकारित्वे निवेशः

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#34]
मित्रवर, लघुदोषे कस्मिंश्चिद् दृष्टे सहकर्तुं शक्नुयाम्। तदर्थं क उचितो मार्गो मतः? यद्युचितम् उपारोपणम् अनुमन्यस्व।

**Comment by vvasuki** [comment]
सम्प्रति, setup.py इत्यत्र lxml संयोजनीयः।

**Comment by avinashvarna** [comment]
एतत् मयापि लक्षितम् । न केवलं lxml, networkx इत्यादयोऽपि योजनीयाः ।

अन्यविषयेषु केचन उपायाः - Python 3 support अपि परीक्षणीयम् । #32 तु अस्त्येव । @kmadathil अपि स्वविचारान् सूचयेत् ।

**Comment by kmadathil** [comment]
@vvasuki : महान् सन्तोषः ! योजितवानहं त्वं सहकर्तृसूच्याम् |‌ इदानीम् उपारोपितुं‌ शक्ष्यसि

**Comment by kmadathil** [comment]
@avinashvarna lxml, networkx इति द्वयं संयोजितं setup.py इत्यस्मिन् |‌ अन्ये दोषाः सन्ति चेत् परिहृत्य संस्करणाङ्कम् (version number)  अपि वर्धयित्वा PyPI इत्यत्र उपारोपयामः

**Comment by vvasuki** [comment]
कृतार्थ्य् अहम् 🙏

**Comment by kmadathil** [comment]
धन्योहं ! तवसहकारेण वर्धतां तन्त्रांशोयम् !
