### ISSUE TITLE
inriaxmlwrapper.py breaking logging for other modules

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#35]
@avinashvarna 
अन्यस्मिन् शाखायां शोधीकृतमिदं मया |‌ b21df2addb1273a80c92b4e69a454897f81b57e7 इति commit दृष्ट्वा  तद् सम्यग् अस्ति चेद् cherry-pick कुरुतात्

**Comment by avinashvarna** [comment]
क्षम्यताम् । मध्यरात्रं कार्यं कुर्वता मया अनवधानतया एवं कृतम् । भवत्परिष्काराः योग्या एव । तान् अन्यत्रापि योजयिष्यामि ।

**Comment by kmadathil** [comment]
चिन्ता मास्तु!‌ bugs आगच्छन्त्येव नूनम् |  ममापि अभ्यासोभवत् logging इत्य्सस्य debugging कर्तुम् :-)
