### ISSUE TITLE
package setup and module import fail: util/data does not exist

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#36]
```
>>> from sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer import SanskritLexicalAnalyzer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/lexical_analyzer/SanskritLexicalAnalyzer.py", line 114, in <module>
    class SanskritLexicalAnalyzer(object):
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/lexical_analyzer/SanskritLexicalAnalyzer.py", line 120, in SanskritLexicalAnalyzer
    forms  = inriaxmlwrapper.InriaXMLWrapper()
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 54, in __init__
    self._load_forms()
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 103, in _load_forms
    self._generate_dict()
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 75, in _generate_dict
    self._get_files()
  File "/usr/local/lib/python2.7/dist-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 60, in _get_files
    os.mkdir(self.data_cache)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/sanskrit_parser/util/data'

```

@avinashvarna any ideas?

**Comment by avinashvarna** [comment]
Looks like you have installed it in a system location where you do not have
write access (did you run `sudo pip install`) ? Could you use
anaconda/virtualenv to have a local environment that you could write to?

To avoid including the large files in the distribution it is downloaded by
the code. Maybe this is an issue @kmadathil had foreseen when he
recommended that we ship all the files.

**Comment by vvasuki** [comment]
- आम्, sudo कृतम्। प्रायेण प्रयोक्तारस् तथैव कुर्वन्ति - तत्कृते मन्ये कल्पनीयम् आनुकूल्यम्।
- setup.py इत्यनेन sudo उपयोगेनैव दत्तान्य् अपि स्थापयितुं शङ्कुमो वा?

**Comment by avinashvarna** [comment]
अग्रे उपायान्तरं चिन्तयाम । data इत्यस्य स्थानपरिवर्तनं (~/.sanskrit_parser/ इति शक्यम् । यथा sklearn इत्यादयो कुर्वन्ति), अथवा तस्य अनेनैव तन्त्रांशेन सह वितरणम् । 
सम्प्रति workaround निमित्तम् -
`sudo python -m sanskrit_parser.util.inriaxmlwrapper hares --loglevel debug`
इति एकवारं करोतु । तदा ताः सञ्चिकाः तत्र स्थाप्यन्ते । तदनु सामान्यक्रमेण उपयोगः शक्यः स्यात् ।

**Comment by kmadathil** [comment]
sudo प्रयुक्तम् इति कारणेन भूतमिदम् |‌ प्रायेण conda/virtualenv वा उपयुज्य
विना sudo एव pip install करणीयमिति मे मतम् |‌ अस्माकं संस्थायां ताददेव
कुर्मः‌ |

नोचेदेवमपि कर्तुं‌ शक्नुमः - लेखनानुज्ञा (write permission) परीक्ष्य
तन्नस्ति चेद् ~/.sanskrit_parser इत्यत्र files स्थापितव्यानि
inriaxmlwrapper इत्यनेन

**Comment by vvasuki** [comment]
@kmadathil @avinashvarna मित्रौ, "नोचेदेवमपि कर्तुं‌ शक्नुमः - लेखनानुज्ञा (write permission) परीक्ष्य 
तन्नस्ति चेद् ~/.sanskrit_parser इत्यत्र files स्थापितव्यानि 
inriaxmlwrapper इत्यनेन " इत्येवोत्तरम् मन्ये। यथा कथमपि pip2यन्त्रं चालयेज् जनः, सफलम् भूयात्। तथा कुरुतम् इत्य् अभिप्रैमि।

**Comment by kmadathil** [comment]
@avinashvarna किं तथा कर्तुं कापि बाधा वर्तते

**Comment by avinashvarna** [comment]
न कापि विशिष्टा बाधा, परन्तु मम अनुभवे, अनेके विकल्पाः सन्ति चेत् अग्रे debugging कठिनतरं स्यात् । यतो हि विभिन्नजनानां सङ्गणकेषु भिन्नानि configurations भविष्यन्ति । अतः सर्वत्र अनुसर्तुं योग्यः एकः सरलः मार्गः चेतव्य इति मम मतम् । तद्दृष्ट्या सर्वदा ~/.sanskrit_parser इत्यत्र स्थापनं सरलतममिति भाति । यदि केनचित् परिवर्तनम् इष्यते (तन्नाम अन्यत्र स्थापनम्), तर्हि $HOME/$USER_HOME इत्यस्य सः स्वयं परिवर्तनं कर्तुम् अर्हति । यदि भवतां विप्रतिपत्तिर्नास्ति, तर्हि अमुमेव मार्गम् अनुसर्तुम् इच्छामि ।

**Comment by vvasuki** [comment]
>‌ यदि भवतां विप्रतिपत्तिर्नास्ति, तर्हि अमुमेव मार्गम् अनुसर्तुम् इच्छामि ।

ओम्

**Comment by kmadathil** [comment]
ओम्

**Comment by avinashvarna** [comment]
I've fixed this issue on the integ branch by moving the data to ~/.sanskrit_parser/.  Can you please check that this works seamlessly (it automatically relocates the data from the old location to the new if it detects that the old folder exists)?

**Comment by kmadathil** [comment]
एवं‌ क्रियते इत्येव भाति | क्रमाङ्कः 0.0.1.dev3 इत्यङ्कित्वा PyPI इत्यत्र उपारोपितवानहम्
