### ISSUE TITLE
Distinguishing between akarmaka and sakarmaka dhAtus

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#41]
Nothing in the lexical tags seems to help for this purpose. 

The morphological analyzer needs to constrain dvitIyA/karma being picked for an akarmaka dhAtu. For example, this : 

Lexical Split: [asti, uttarasyAm, diSi, de, avatA, AtmA]
Valid Morphologies
[(asti, ('as#1', set([kartari, law, ekavacanam, prATamikaH, praTamapuruzaH]))), (uttarasyAm, ('uttara#2', set([strIliNgam, saptamIviBaktiH, ekavacanam]))), (diSi, ('diS#2', set([strIliNgam, saptamIviBaktiH, ekavacanam]))), (de, ('da', set([dvivacanam, dvitIyAviBaktiH, strIliNgam]))), (avatA, ('avat', set([puMlliNgam, tftIyAviBaktiH, kartarivartamAnakfdanta-parasmEpadI, kartari, ekavacanam, prATamikaH, kfdantaH]))), (AtmA, ('Atman', set([puMlliNgam, praTamAviBaktiH, ekavacanam])))]

(karaka/vibhakti are not bijective, that is a different issue for which the morphological analyzer needs extension)

**Comment by avinashvarna** [comment]
कृदन्तरूपमालायां एष विषयः दत्तः (यथा [अत्र](https://raw.githubusercontent.com/sanskrit-coders/stardict-sanskrit/master/sa-vyAkaraNa/kRdanta-rUpa-mAlA/mUlam/kRdanta-rUpa-mAlA.tsv)) । ततः scrape कर्तुं शक्येत, परन्तु केषाञ्चित् धातूनां भिन्नेषु सन्दर्भेषु सकर्मकत्वम् / अकर्मकत्वं वा परिवर्तते, विशिष्य उपसर्गयोगे । अतः एतम् अंशं सरलतया नियमरूपेण कथम् उपयोक्तुं शक्यते इति चिन्तयन्नस्मि ...

**Comment by kmadathil** [comment]
> ततः scrape कर्तुं शक्येत
तावत्करणात् आरब्धुम् अर्हामः |‌

कृदन्तरूपमालाया अन्या अपि उपयोगा भवेयुर् इति चिन्तयामि

**Comment by kmadathil** [comment]
[इदम्](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-vyAkaraNa/dhAtu-pATha-kRShNamAchArya/mUlam/Dhatu%20Patha%20%E0%A4%95%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A3%E0%A4%BE%E0%A4%9A%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%AF%E0%A4%B8%E0%A5%8D%E0%A4%AF%20%E0%A4%95%E0%A5%83%E0%A4%A4%E0%A5%87%E0%A4%83%20-%20Sheet1.tsv) द्र्ष्टवान् अहं यदृच्छया | तत् scrape कर्तुं सुकरतरं‌ मन्ये 

@vvasuki - मित्र विश्वास, को भवतो अभिप्रायो विषयेस्मिन् ( तस्मात् scrape कृत्वा सकर्मकत्वनिर्धारणविषये)

**Comment by vvasuki** [comment]
युक्तन्तद् बन्धो - tsv एवेति मन्ये। [एतदप्य्](https://docs.google.com/spreadsheets/d/1gAivrf94kRpK5rSADkvlTNlq3dRAcUvIneLY-Y1eCT8/edit#gid=0) अस्ति।

**Comment by kmadathil** [comment]
DhatuWrapper.py इति utility लिखितं मया तदर्थम् |‌ 
[एतस्यां सञ्चिकायां](https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-vyAkaraNa/dhAtu-pATha-kRShNamAchArya/mUlam/) चतुर्षु राजिषु दोषाः‌ दृश्यन्ते - क्रमेण १०६४,१०६५,१०६६, १२४५ तमासु

**Comment by kmadathil** [comment]
Rule added.
(not using the original asti example, as there is असु क्षेपणे which is sakaramaka, and we cannot currently distinguish between similar dhAtus)

$ python -m sanskrit_parser.morphological_analyzer.SanskritMorphologicalAnalyzer 'mAM svapimi' --debug
Input String: mAM svapimi
Input String in SLP1: mAM svapimi
Start Split: 2017-10-03 21:59:50.885957
End DAG generation: 2017-10-03 21:59:50.910354
End pathfinding: 2017-10-03 21:59:50.910791
Splits:
Lexical Split: [mAm, svapimi]
No valid morphologies for this split
