### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by codito** [kmadathil/sanskrit_parser#44]
The readme docs mention support for python 3 as work in progress. Is there an existing branch or fork with this work? Would love to try it out.

**Comment by kmadathil** [comment]
Not yet. We've tried to eliminate as much Python 2 dependency as possible, but we've not really checked it out. If you're willing to try, that'd be much appreciated!

**Comment by codito** [comment]
Sure, I will try out and get back on this issue.

**Comment by codito** [comment]
Created a PR https://github.com/kmadathil/sanskrit_parser/pull/45 for python3 port. Appreciate review and feedback.

**Comment by codito** [comment]
Should we add a CI for running tests for both py2 and py3 in this repo? It will ensure scenarios do not regress with changes.

**Comment by kmadathil** [comment]
PR has been merged, thanks a lot!
CI is being discussed in #47 

Closing this.
