### ISSUE TITLE
जश्त्वं +‌ चुत्वम् 

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#50]
python -m sanskrit_parser.lexical_analyzer.sandhi --split kasyacijjantoH 7
Splitting {0} at {1} kasyacijjantoH 7
set([(u'kasyaciC', u'jantoH'), (u'kasyacij', u'jantoH'), (u'kasyacid', u'jantoH'), (u'kasyacic', u'jantoH'), (u'kasyacij', u'dantoH'), (u'kasyaciJ', u'jantoH')])

कस्यचित् +‌ जन्तोः इत्यप्यपेक्ष्यते split

त् - >‌ द्   ( झलां ज्शोन्ते / जशि  ) 
द् - >‌ ज्   (श्चुना श्चु )
कस्यचिज्जन्तोः

**Comment by avinashvarna** [comment]
I had fixed this on my branch a while ago. Will merge with master.

**Comment by avinashvarna** [comment]
Fixed on test_improvement branch. Will close when merged with master.

**Comment by kmadathil** [comment]
Merged with master.
