### ISSUE TITLE
Remove old references/branches from repo

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#51]
Looking at the [network graph of our repo](https://github.com/kmadathil/sanskrit_parser/network) it appears that the following old refs/branches are not needed as they have been merged with master:
origin/dag
dag-nx
integ
If there are no objections, I will remove these branches from the repo, just to reduce clutter.

**Comment by kmadathil** [comment]
Sure. Please do. We could consider retaining integ (and keeping it up to date) with master as our normal integration branch as we've done in the past

**Comment by avinashvarna** [comment]
Since integ is a direct ancestor of master, it would get fast-forwarded (i.e. the ref would get moved to the same point as master). I think the equivalent would be to just branch master when needed and call it integ. However, I've left it for now.

**Comment by kmadathil** [comment]
Ok, then let's remove it.

**Comment by avinashvarna** [comment]
Done.
