### ISSUE TITLE
Fix module names to match convention

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#52]
MaheshvaraSutras DhatuWrapper etc.. should be renamed maheshvara_sutras dhatu_wrapper etc. Dont forget the rst files in https://github.com/kmadathil/sanskrit_parser/tree/master/docs ..

Uniform conventions are good - avoid confusions while using code, pares down warning lines in linters so that one can focus on genuine problems etc..

**Comment by codito** [comment]
Good idea! We can adhere to the `pep 8` and `pep 257` python standards. Few tools like [`flake8`](https://pypi.python.org/pypi/flake8) and [`flake8-docstrings`](https://pypi.python.org/pypi/flake8-docstrings) can help us.

**Comment by kmadathil** [comment]
Want to take this up, @codito ? If not, I can

**Comment by drdhaval2785** [comment]
Atom with flake8 works extremely well as python IDE with PEP8 validation.

**Comment by vvasuki** [comment]
I find intellij IDE's py plugin very good - you can suppress warnings for particular statements and ignore certain rules altogether with a few clicks - and the "code analysis" runs before every check-in.

**Comment by codito** [comment]
@kmadathil sure, I can take a shot at it in the coming week.

**Comment by vvasuki** [comment]
One thing is pending (as I'd commented) - SanskritMorphologicalAnalyzer.py needs to be renamed.

**Comment by codito** [comment]
Will take up other modules in next PR.

**Comment by kmadathil** [comment]
Renamed sanskrit_morphological_analyzer
