### ISSUE TITLE
User-friendliness for visargas, anusvAras etc. 

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#56]
Currently, all the tools/API expect word ending visargas to be supplied as 's' due to the fact that the INRIA db stores it that way. This is an internal detail and should not be exposed to the end user/external API. 
One idea would be to extract the changes applied to the UoHD data and convert it into a utility to handle such conversions. This would also take care of trailing anusvAras etc.

**Comment by kmadathil** [comment]
Let's enumerate the issues
 1) sandhi / tag expects sakArantas/rakArantas to be entered as such, not with visargas (रामस्, पुनर् rather than रामः , पुनः ). LexicalAnalyzer and MorphologicalAnalyzer are ok with ending visargas.
 2) Sentence ending anusvAras are rejected without warning by LexicalAnalyzer and MorphologicalAnalyzer 

Please add more. We need a solution that works as the average user would "expect", and yet not be wrong from a grammatical perspective. My initial thoughts would be to match a few such standard patterns (as @avinashvarna mentioned above), throw a warning, and helpfully make the suggested modifications ourselves.

For example, 
1) we could handle an ending anuswara by throwing out a warning and transforming it into a makara ourselves.
2) An ending visarga could be handled by throwing a warning, then replacing it with a स् and र् in succession

**Comment by avinashvarna** [comment]
For Issue 1, doesn't LexicalAnalyzer expect sakArAntas/rephAntas, since it would lookup tags? 

I need to test and think about the sandhi module a bit more, but I feel that it would work with visargas. E.g.
```bash
$ python -m sanskrit_parser.lexical_analyzer.sandhi --split rAmaHgacCati 4
Splitting rAmaHgacCati at 4
set([(u'rAmas', u'gacCati'), (u'rAmaH', u'gacCati'), (u'rAmar', u'gacCati')])
```

Modifications:
2a. I think 2 should also be extended to include input ending with 'o'. 
3? Possibly cases where the ending विसर्ग undergoes लोप. For example, I can imagine someone coming across "दारा इति" and only enter the first word, because they know what the second is, without realizing that it will throw off the analysis. We already do this to clean up the uohd data.

**Comment by kmadathil** [comment]
1. As a tagger, yes. As a sentence splitter, no.
(master)$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split gacCatirAmaH
Input String: gacCatirAmaH
Input String in SLP1: gacCatirAmaH
Start Split: 2017-11-30 12:39:03.425789
End DAG generation: 2017-11-30 12:39:03.431968
End pathfinding: 2017-11-30 12:39:03.433720
Splits:
[gacCa, tirAmas]
[gacCati, rAmas]
[gacCa, tira, Amas]
[gacCat, irA, Amas]
[gacCati, rA, Amas]

**Comment by kmadathil** [comment]
2a. yes. An ending "o" should result in a warning, and a 's' replacement

3a. विसर्गलोपः - technically that's यलोपः :-) , but I won't press that point since we're talking about not burdening folks with Paninian intricacies. In the UoHD transformations, we do that where we have clear context - a mismatch in the final visarga in the full or the split.  It would be slightly more involved here, I think. My suggestion is - if a vowel ending input doesn't result in a split, we throw a warning, and try with a visarga appended.

**Comment by kmadathil** [comment]
८ . ३ . १७ भोभगोऽघोऽपूर्वस्य योऽशि 
८ . ३ . १९ लोपः शाकल्यस्य
इत्याभ्याम् "दारा इति" । 
एताभ्यामेव "राम इह" "पुनरिह"‌  इत्यनयोर्भेदः  जायते !

**Comment by codito** [comment]
@kmadathil @avinashvarna thanks for explaining issue with #57 at great detail.

Should the user interfaces choose to normalize (or auto correct) user input? E.g. normalization is default at the Web and CLI entrypoints. May be through a configuration like `SanskritLexicalAnalyzer.normalize=True` which could then use an API internally like `SanskritWord.normalize()` before starting the analysis (may be similar to `string.strip()`). The base API will have the logic to auto correct these inputs.

We could possibly keep the library grammatically correct for all scenarios, unless the consumer explicitly asks for a normalization.

**Comment by avinashvarna** [comment]
Technically, the lexical analyzer does not do any conversions. It handles the ending visarga because the sandhi module is returning स् in the reverse direction (we had imposed this requirement):
```bash
$ python -m sanskrit_parser.lexical_analyzer.sandhi --split rAmaH 4
Splitting rAmaH at 4
set([(u'rAmaH', u''), (u'rAmas', u''), (u'rAmar', u'')])
```
This reaffirms my thinking that the sandhi module can handle ending visargas.

@codito Agreed. We are all aligned on the need for normalization at the entry points. I think that the same should apply at *exit* points as well, when returning information to the user.

**Comment by kmadathil** [comment]
by खरवसानयोर्विसर्जनीयः , we get the transformation स् ->‌र् ->‌ ः at the end of the sentence, which is why we needed splitting ः‌ at the end to return स्

**Comment by kmadathil** [comment]
Perhaps a strict mode to go into "grammarian" style input and output, with the norm being normalized input and output is the best way to go.

**Comment by avinashvarna** [comment]
Ok, I'll take a stab at it.

**Comment by avinashvarna** [comment]
Started an implementation on [user_friendliness](https://github.com/kmadathil/sanskrit_parser/tree/user_friendliness) branch. Currently, I've only added support for sandhi, Lexical Analyzer and the REST API. If we are OK with this, I will update Morphological analyzer as well. Please review.

Some examples:
**Default behavior: User-friendly input/output. Correctly splits पश्यैतां (#57), returns results with visargas**
```bash
$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer paSyEtAM --split
Input String: paSyEtAM
Input String in SLP1: paSyEtAm
Splits:
[paSyA, etAm]
[paSyE, tAm]
[paSyA, EtAm]
[paSya, etAm]
[paSya, EtAm]

$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer himAlayonAma --split
Input String: himAlayonAma
Input String in SLP1: himAlayonAma
Splits:
[hima, AlayaH, nAma]
[hi, mAlayaH, nAma]
[hima, alayaH, nAma]
[hima, AlayaH, anAma]
[himAH, layaH, nAma]
[hi, mAlayaH, anAma]
[hima, alayaH, anAma]
[himAH, layaH, anAma]
[hi, mAH, layaH, nAma]
[hima, Alaya, Una, Ama]
```

**Do not apply normalization by passing in --dont-normalize option:**
```bash
$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer paSyEtAM --split --dont-normalize
Input String: paSyEtAM
Input String in SLP1: paSyEtAM
No Valid Splits Found

$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer himAlayonAma --split --dont-normalize
Input String: himAlayonAma
Input String in SLP1: himAlayonAma
Splits:
[himAs, layas, anAma]
[hima, alayas, anAma]
[himAs, layas, nAma]
[hi, mAlayas, anAma]
[hima, Alayas, anAma]
[hima, alayas, nAma]
[hi, mAlayas, nAma]
[hima, Alayas, nAma]
[himAs, laya, Una, Ama]
[himAs, layas, na, Ama]

```

**Comment by codito** [comment]
:+1: minor suggestion: will `--no-normalize` be more natural command line option? We can add a few unit tests for normalization module.

**Comment by kmadathil** [comment]
Is "normalize" the right name to expose externally? I'd  request to change the mode name to strict (with the normalize/denormalize functions remaining as they are).

External option --strict (default=False). 
__init__ has an option strict=False. 
```
If not strict:
  # Call normalize
```

The context manager is cool within the context of the main program. Will it be easy to use for someone who imports our modules? Should we have a cleaner way of denormalizing the output? Maybe findAllPaths should denormalize its output if the constructor hasn't been called with strict=True?

**Comment by avinashvarna** [comment]
"strict" sounds quite general as well. Does that mean only the input/output uses strict rules or some internal operations are strict as well? Would adding some qualifier, e.g. strict-input be better?

The context manager is the only way that I could think of to get print statements to denormalize the output correctly, since `__str__` does not take any other inputs. As it is only for printing, my opinion is that other modules that import our modules should be able to use it in a straightforward manner. Some standard python classes/modules do the same to control print behavior, e.g. see examples 8 & 9 using the decimal module in the [PEP](https://www.python.org/dev/peps/pep-0343/#examples). We can rename the context manager function to be something more user friendly instead of denormalization. 

For programmatic control, it is always possible to call `devanagari` or `canonical` methods of `SanskritObject` with `denormalize=True/False` to get the desired output.

This seemed the cleanest way to have it apply everywhere since `SanskritObject` is the base class used for everything. If we add it to `findAllPaths` or the LexicalAnalyzer class, wouldn't we have to add a denormalization option to every other class? Also, since it is not really a core function of any of the other classes, I don't think it should be a part of them from an OOP perspective. I am open to other suggestions.

**Comment by kmadathil** [comment]
`--strict-io` then? 
I'm ok with using `canonical` or `devanagari` methods programmatically, so that deals with the comment about the context manager. 
I think this works.

**Comment by avinashvarna** [comment]
Closing as PR has been merged. Please reopen if necessary.
