### ISSUE TITLE
पश्यैतां analysis

### ISSUE THREAD

**Issue by codito** [kmadathil/sanskrit_parser#57]
```sh
# Sandhi split works as expected
> python -m sanskrit_parser.lexical_analyzer.sandhi --split paSyEtAM --all
All possible splits for paSyEtAM
{('paSya', 'EtAM'), ('paSya', 'etAM'), ('paSyA', 'EtAM'), ('paSi', 'EtAM'), ('paSyA', 'etAM'), ('paSyE', 'tAM'), ('paSyEt', 'AM'), ('paSyEtA', 'aM'), ('paSyEta', 'aM'), ('paSyEta', 'AM'), ('paSyEtAM', ''), ('paSyEtA', 'AM'), ('paSy', 'EtAM'), ('paSyEtA', 'M'), ('pa', 'SyEtAM'), ('paSI', 'EtAM'), ('p', 'aSyEtAM')}

# Bug? SanskritLexicalAnalyzer says there isn't valid split
> python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer paSyEtAM                                                        master [62a8f67] untracked
Input String: paSyEtAM                                                                                                                                         
Input String in SLP1: paSyEtAM                                                                                                                                 
None 

> python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer paSyEtAM --split                                                master [62a8f67] untracked
Input String: paSyEtAM                                                                                                                                         
Input String in SLP1: paSyEtAM                                                                                                                                 
Start Split: 2017-11-30 06:05:48.280214                                                                                                                        
End DAG generation: 2017-11-30 06:05:48.282300                                                                                                                 
No Valid Splits Found 
```

**Comment by kmadathil** [comment]
(master)$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split paSyEtAm
Input String: paSyEtAm
Input String in SLP1: paSyEtAm
Start Split: 2017-11-30 09:56:33.599350
End DAG generation: 2017-11-30 09:56:33.602880
End pathfinding: 2017-11-30 09:56:33.604186
Splits:
[paSyA, EtAm]
[paSya, EtAm]
[paSyA, etAm]
[paSyE, tAm]
[paSya, etAm]
 
(master)$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split paSyEtAM
Input String: paSyEtAM
Input String in SLP1: paSyEtAM
Start Split: 2017-11-30 09:56:50.168743
End DAG generation: 2017-11-30 09:56:50.171327
No Valid Splits Found

Bonus:
(master)$ python -m sanskrit_parser.morphological_analyzer.SanskritMorphologicalAnalyzer  paSyEtAm
Input String: paSyEtAm
Input String in SLP1: paSyEtAm
Start Split: 2017-11-30 09:58:25.971035
End DAG generation: 2017-11-30 09:58:26.062365
End pathfinding: 2017-11-30 09:58:26.063717
Splits:
Lexical Split: [paSya, etAm]
Valid Morphologies
[(paSya, ('paS', set([low, kartari, ekavacanam, prATamikaH, maDyamapuruzaH]))), (etAm, ('etad', set([dvitIyAviBaktiH, ekavacanam, strIliNgam])))]
Lexical Split: [paSyA, etAm]
No valid morphologies for this split
Lexical Split: [paSya, EtAm]
No valid morphologies for this split
Lexical Split: [paSyE, tAm]
Valid Morphologies
[(paSyE, ('paS', set([low, kartari, ekavacanam, prATamikaH, uttamapuruzaH]))), (tAm, ('tad', set([dvitIyAviBaktiH, ekavacanam, strIliNgam])))]
Lexical Split: [paSyA, EtAm]
No valid morphologies for this split
End Morphological Analysis: 2017-11-30 09:58:26.150823

**Comment by kmadathil** [comment]
Please see above. The problem is with the word-ending anuswara, which should've been a makAra. etAM is not considered a valid form, and therefore will be rejected.

**Comment by kmadathil** [comment]
And ... just for confirmation that  मो Sनुस्वारः‌ (हलि)‌‌ is handled correctly, we check पश्यैतांयुवतीम्

(master)$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split paSyEtAMyuvatIm
Input String: paSyEtAMyuvatIm
Input String in SLP1: paSyEtAMyuvatIm
Start Split: 2017-11-30 10:08:28.197479
End DAG generation: 2017-11-30 10:08:28.207558
End pathfinding: 2017-11-30 10:08:28.209544
Splits:
[paSyE, tAm, yuvatIm]
[paSya, etAm, yuvatIm]
[paSyA, EtAm, yuvatIm]
[paSya, EtAm, yuvatIm]
[paSyA, etAm, yuvatIm]

**Comment by avinashvarna** [comment]
While the behavior is expected, it is not user-friendly. The average user of the program through the HTML UI front-end we are developing, may come across पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ..., decide to look up पश्यैतां, and get no useful information. This is related to #56 (in fact, trailing anusvaaras are called out in that issue). Similar results would be expected if one tried 'rAmo'.

If we had a pre- and post-processing stage at all the interfaces exposed by our modules, that would handle such conversions, then it would also address this specific problem. We could continue the discussion in #56 to keep it consolidated.

**Comment by kmadathil** [comment]
Moving the discussion to #56
