### ISSUE TITLE
Setup github.io to serve from docs

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#59]
docs folder has all the built  files, but the repo admin [needs to fix ](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)the settings so as to tell github.io to serve docs from there. Then, http://kmadathil.github.io/sanskrit_parser/build/html/index.html will have the docs, and we can fix README to refer to that page for usage instructions.

**Comment by kmadathil** [comment]
कृतम् . दृश्यते  http://kmadathil.github.io/sanskrit_parser/build/html/index.html  इत्यस्मिन् सङ्केते अस्माकं docs!
