### ISSUE TITLE
Reuse potential

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#6]
Another candidate for reuse - https://github.com/sanskrit/sanskrit

Haven't investigated too much, but appears to have an API for adding sandhi rules that can later be used to split words.

**Comment by kmadathil** [comment]
Good, please check if this can be used to get us better sandhi reversal.

**Comment by avinashvarna** [comment]
Will close this issue as we already implemented a sandhi class inspired by ideas from this project.
