### ISSUE TITLE
Fix all those javascript warnings..

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#62]
I am shown lots of lint warnings and errors in the javascript code.. Must be fixed lest it lead to time drains in the future.

**Comment by vvasuki** [comment]
Actually, I don't think you get rewards commensurate to the extra effort of having a fancy UI given that swagger UI is already quite good.

**Comment by avinashvarna** [comment]
Fixed lint warnings in javascript code. I did not change the jslint errors regarding use of x ? y : z on the same line since I feel that most programmers recognize that syntax. Other linters don't seem to have the same concern, so will live with it for now.
