### ISSUE TITLE
Make local sanskrit_data dump py-version neutral

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#66]
Errors such as https://github.com/kmadathil/sanskrit_parser/issues/60#issuecomment-350762365 would be confusing for users. Data dumps should not depend on consumer-software version (py version in this case) - a neutral format, such as json should be used.

**Comment by avinashvarna** [comment]
I think this is the same as #61. If we move the data to standard DB interfaces, it will solve this problem as well. Any objection to keeping the discussion consolidated in #61?

**Comment by vvasuki** [comment]
You mean that it is same as https://github.com/kmadathil/sanskrit_parser/issues/64 instead? "What you store" (#64) is different from "how you access/ store" (#61). No objection to closing this and merging with #64
