### ISSUE TITLE
Pip install error - MacOS High Sierra

### ISSUE THREAD

**Issue by vikramiyer** [kmadathil/sanskrit_parser#80]
` byte-compiling /Library/Python/2.7/site-packages/networkx/generators/random_graphs.py to random_graphs.pyc
    byte-compiling /Library/Python/2.7/site-packages/networkx/generators/joint_degree_seq.py to joint_degree_seq.pyc
    running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-kjSUrU/networkx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h2owcw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-kjSUrU/networkx/`

Running as root (sudo pip install)

**Comment by codito** [comment]
Appears to be a permissions issue. Does this help? https://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade

**Comment by vikramiyer** [comment]
I can give that a try, but apprehensive about disabling system integrity protection.

**Comment by kmadathil** [comment]
There are various options there - the simplest one seems to be to do a user specific installation using --user.

Perhaps the cleanest is to create a virtual environment using brew or anaconda. I prefer to work in an anaconda virtual environment (though I'm not on MacOs)

**Comment by vikramiyer** [comment]
Yes `pip install sanskrit_parser --user` worked on my Mac.
