### ISSUE TITLE
R-kArAnta pancamI/ShaShThI

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#83]
INRIA db मध्ये केवलं ऋकारान्तशब्दानां पञ्चमी-एकवचनान्तरूपाणि, षष्ठी-एकवचनान्तरूपाणि रेफान्तरूपेण दर्शितानि । तन्नाम पितुर् मातुर् इत्यादि । परन्तु अन्यत्र सर्वत्र पञ्चमी-षष्ठी-विभक्तिरूपाणि 'स्-कारान्तेन' रक्षितानि । अस्य किमपि विशेषकारणं स्यात् किम् ? sanskrit_util/sanskrit_data INRIA इत्यनयोः समन्वयकार्ये मग्नोऽहम् एतल्लक्षितवान् । sanskrit_data कोषे परिवर्तनीयम् उत स्-कारान्त एव उचितः ?

**Comment by kmadathil** [comment]
तत्र रकारान्तरूपाण्येव साधूनि किल 
पितृ +‌ ङस् 
पितृ +‌अस् (‌तस्य लोपः)
पितु + स्  (उ आदेशः पूर्वापरयोः - ऋत उत् )
पितुर् +‌ स्  (र आगमः - उरण् रपरः)
पितुर्  (सलोपः - रात् सस्य )
पितुः (खरावसानयोर् विसर्जनीयः)

यतोहि वयं अवसाने भवितव्यं विसर्जनीयादेशं न पश्यामः INRIA db इतयस्मिन् , अत्र रकारान्ताः एव साधूनि 

अन्यत्र सकारान्ताः‌ सधूनि 
कवि +‌ ङस् 
कवे +‌ ङस्
कवे +‌अस् (गुणः - घेर्ङिति )‌
कवेस् ( एङः पूर्वरूपादेशः पूर्वापरयोः  - ङसिङसोः )
कवेः (खरवसानयोर् विसर्जनीयः)

**Comment by avinashvarna** [comment]
सत्यम् । "अतो रोरप्लुतादप्लुते" इत्यस्य अत्र प्रवर्तनं नैव संभवति । अतः सन्धिप्रक्रियायां न तावान् भेदः । अन्यत् किमपि विशेषकारणं स्यात् किम् इति अत एव अपृच्छम् । अस्तु । वयमपि रेफान्तत्वेन रक्षिष्यामः ।
