### ISSUE TITLE
vedAntashAstraprakriyAM_Split 

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#86]
Issue reported by @drdhaval2785

vedAntashAstraprakriyAM_Split
--- Please enter your issue below ---
 
1. vedAnta is a word in itself. In current scenario, it is not shown. 

2. pra kri yAm does not make sense.

**Comment by kmadathil** [comment]
This is what I see

(master)$ python -m sanskrit_parser.morphological_analyzer.SanskritMorphologicalAnalyzer vedAntashAstraprakriyAM 
Input String: vedAntashAstraprakriyAM
Input String in SLP1: vedAntaSAstraprakriyAm
Start Split: 2018-02-13 14:12:29.959290
End DAG generation: 2018-02-13 14:12:29.987365
End pathfinding: 2018-02-13 14:12:29.988621
Splits:
Lexical Split: [veda, anta, SAstra, prakriyAm]
Valid Morphologies
[(veda, ('vid#1', set([kartari, ekavacanam, uttamapuruzaH, prATamikaH, liw]))), (anta, ('anta', set([samAsapUrvapadanAmapadam]))), (SAstra, ('SAstra', set([samAsapUrvapadanAmapadam]))), (prakriyAm, ('prakriyA', set([strIliNgam, dvitIyAviBaktiH, ekavacanam])))]
[(veda, ('vid#1', set([kartari, praTamapuruzaH, ekavacanam, prATamikaH, liw]))), (anta, ('anta', set([samAsapUrvapadanAmapadam]))), (SAstra, ('SAstra', set([samAsapUrvapadanAmapadam]))), (prakriyAm, ('prakriyA', set([strIliNgam, dvitIyAviBaktiH, ekavacanam])))]
Lexical Split: [veda, anta, SAstra, pra, kriyAm]
No valid morphologies for this split
Lexical Split: [veda, anta, SAstra, pra, kri, yAm]
No valid morphologies for this split
End Morphological Analysis: 2018-02-13 14:12:30.064625

**Comment by kmadathil** [comment]
@drdhaval2785:

1) Yes, we should have vedAnta as a word. We're working on enhancing the forms in the db, as in #82 
2) pra kri yAm is a valid sandhi split, but doesn't make sense, as you said. That's why it's shown by the lexical analyzer, but rejected by the morphological analyzer as above.

**Comment by avinashvarna** [comment]
On the sanskrit_util branch, the lexical analyzer split itself is more natural:
```
Input = vedAntaSAstraprakriyAm
[vedAntaSAstra, prakriyAm]
[vedAnta, SAstra, prakriyAm]
[vedAntaSAstra, pra, kriyAm]
[vedAntaSAstra, prakriyA, Am]
[vedAntaSAstra, prakri, yAm]
[vedAntaSAstra, prakriyA, am]
[vedAm, ta, SAstra, prakriyAm]
[vedAnta, SAstf, a, prakriyAm]
[vedAnta, SAstra, pra, kriyAm]
[vedAntaSAstra, pra, kriya, Am]
```

Let us promote this branch to master as mentioned in #82, as the pros seem to outweigh the cons.

**Comment by avinashvarna** [comment]
With PR #90 this has been fixed on master:
```
(master) $ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer vedAntashAstraprakriyAM --split  Input String: vedAntashAstraprakriyAM
Input String in SLP1: vedAntaSAstraprakriyAm
Start Split
End DAG generation
End pathfinding 1527959392.03
Splits:
[vedAntaSAstra, prakriyAm]
[vedAnta, SAstra, prakriyAm]
[vedAntaSAstra, prakriyA, am]
[vedAntaSAstra, prakri, yAm]
[vedAntaSAstra, prakriyA, Am]
[vedAntaSAstra, pra, kriyAm]
[vedA, Anta, SAstra, prakriyAm]
[vedAnta, Sa, astra, prakriyAm]
[vedAnta, SAstra, prakriyA, am]
[vedAntaSAstra, prakri, yA, am]
-----------
Performance
Time for graph generation = 1.314000s
Total time for graph generation + find paths = 1.314000s
```

Closing this issue. Please reopen if necessary.
