### ISSUE TITLE
Check manually entered test splits

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#87]
To prevent the travis CI tests from failing due to a very long run-time on the sanskrit_util branch, I have reduced the number of paths that the test script generates and commented out the fallback to > 10000 paths that would trigger the findAllPaths routine. Most of the tests work correctly even with this reduced path number, and currently only 4 tests fail (https://travis-ci.org/kmadathil/sanskrit_parser/jobs/348748061). All 4 of these correspond to data that was manually entered. 

The first test looks for tags of gaNeshaH. Since the sanskrit_util branch uses both the sanskrit_data and INRIA dbs to lookup tags, it returns duplicates, which causes the assertion to fail. Can we mark this test as xfail due to the duplication? Once we merge all INRIA data into the sanskrit_data db, this duplication should no longer happen.

The remaining three failing tests are due to splits that were perhaps set up to correspond to the INRIA db data. Since the sanskrit_util branch produces higher quality splits, these need to be updated.

@kmadathil Do you want to take a look at these 4 tests and update them, since you added them? If you are busy, I can also update them.

**Comment by kmadathil** [comment]
Since these are manual tests, I'll update them in the sanskrit_util branch
with the right values later today.

**Comment by kmadathil** [comment]
No issues seen in manual tests now, but I am seeing errors in the automated tests (I've not changed anything there). I'll look into it sometime late evening.

**Comment by avinashvarna** [comment]
I think that one or two cases have many possible splits of the same length due to the larger vocabulary. Since the shortest_simple_paths algorithm is not guaranteed to return paths in the same order always, for these cases sometimes the correct split happens to be in the top 100, and sometimes it isn't. This is supported by the fact that these tests pass sometimes and fail occasionally.

I am working on a scoring mechanism that can be used to resort the splits which might help get around this issue. For now, I think we need not spend too much time on these failures right now.

**Comment by kmadathil** [comment]
Ok, can we close this then?
