### ISSUE TITLE
Add BhagavadgIta testcase

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#89]
https://sanskritdocuments.org/doc_giitaa/gitAanvayasandhivigraha.html?lang=sa 

Has splits.

**Comment by poojapi** [comment]
I can look into this if not already taken by someone else.

**Comment by poojapi** [comment]
Is this task still open?

**Comment by kmadathil** [comment]
Very much so. Appreciate if you can take it up. There's an initial test in there, it needs to be triaged so we can fix the genuine fails.

**Comment by poojapi** [comment]
I will work on it then. Thanks!

**Comment by kmadathil** [comment]
@poojapi Whichever way works for you is fine. 
My preference is to go for the false fails first - that'll remove a lot of the 600 fails, then figure out the true fails. However, if you think it's more productive to report the true fails, please go for it. Both move us towards the end goal

**Comment by poojapi** [comment]
I'm done with the task. Wrote a script to parse the json output in the logs to print out the false positives and the failures. All of them are false positives. There is not a single really failed entry.  Will raise a PR for the failure analyser I wrote.

**Comment by kmadathil** [comment]
@poojapi 
The file  `generate_bg_LexicalAnalyzer_pass_fail.py` generates the pass/fail list. What it does is, parse "sandhi_test_data/gitAanvayasandhivigraha.itx" and generate a test json object from the output. We then call `test_splits` with the 'full' and 'split' (which are the input string and the expected split as parsed from the file), which returns true or false depending on whether the  internally generated `splits` contains the expected split (the `_in_splits` call).  Since we don't write the generated split to the error file (to keep it tractable to parse), we cannot determine whether a fail is true/false by only looking at the fail file. 
What we need to do is 
  1) Parse the fail file and run it through the cmd line 
  2) Manually look at the output that the command line gives for each input in the fail file ("full") can compare it with the expected ("split") output. 
  3) Report if you see an actual issue. 
You could choose to replace the command line with a script - might be faster.

Now it's highly likely that most fails are due to a limitation in the rather simple translator I wrote for the itx input to convert it into runnable inputs for us. The translator might be outputting junk in many cases. 

Also, this script is out of date w.r.t our new api - called out in  #123 .

**Comment by kmadathil** [comment]
So, if you want to start from scratch and revamp the `generate_bg_LexicalAnalyzer_pass_fail.py` to use our new API interface, and take a look at the way I'm translating from itx into inputs for our sandhi splitter that might be more interesting for you. While doing that, you might just eliminate most of the fails by finding errors in the translator.

**Comment by poojapi** [comment]
Now i get it. I actually went through the logs and had some doubt. Your comment clarified them. I will do this as indicated and get back to you. Thanks for the explanation. Makes a lot of things clear.

**Comment by kmadathil** [comment]
@poojapi
Correct. That rewrite is what #123 is about. If you change the scripts to match the new API, you'd have solved that too. Let's change the name too - say, generate_bg_sandhi_pass_fail.py etc.

**Comment by kmadathil** [comment]
@poojapi  - Are you still looking at this?

**Comment by poojapi** [comment]
@kmadathil Sorry, I had lost touch due to some other commitments. Will work on it this weekend.

**Comment by kmadathil** [comment]
No rush, just checking. Please do it at your leisure.

**Comment by kmadathil** [comment]
This has been superseded by #153 . SandhiKosh includes BhagavadGita testcases, and they have made it easy to use. We already have a working version on the `multigraph` branch.
