### ISSUE TITLE
Sanskrit Util Issue with sqlalchemy 

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#95]
____________ ERROR collecting tests/test_SanskritLexicalAnalyer.py _____________
tests/test_SanskritLexicalAnalyer.py:9: in 
from sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer import SanskritLexicalAnalyzer
sanskrit_parser/lexical_analyzer/sanskrit_lexical_analyzer.py:10: in 
from sanskrit_parser.util.lexical_lookup_factory import LexicalLookupFactory
sanskrit_parser/util/lexical_lookup_factory.py:8: in 
from sanskrit_parser.util.sanskrit_data_wrapper import SanskritDataWrapper
sanskrit_parser/util/sanskrit_data_wrapper.py:11: in 
import sanskrit_util.analyze
.tox/py36/lib/python3.6/site-packages/sanskrit_util/init.py:11: in 
from .context import Context
.tox/py36/lib/python3.6/site-packages/sanskrit_util/context.py:20: in 
from .schema import Base, EnumBase, GenderGroup
.tox/py36/lib/python3.6/site-packages/sanskrit_util/schema.py:357: in 
class PrefixedModifiedRoot(PrefixedRoot, ModifiedRoot):
.tox/py36/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py:65: in init
as_declarative(cls, classname, cls.dict)
.tox/py36/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py:116: in as_declarative
MapperConfig.setup_mapping(cls, classname, dict)
.tox/py36/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py:144: in setup_mapping
cfg_cls(cls, classname, dict)
.tox/py36/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py:174: in init
self._setup_inheritance()
.tox/py36/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py:509: in _setup_inheritance
"Class %s has multiple mapped bases: %r" % (cls, inherits))
E sqlalchemy.exc.InvalidRequestError: Class <class 'sanskrit_util.schema.PrefixedModifiedRoot'> has multiple mapped bases: [<class 'sanskrit_util.schema.PrefixedRoot'>, <class 'sanskrit_util.schema.ModifiedRoot'>]

Workaround - forcing sqlalchemy to 1.0.11 fixes this. @avinashvarna , this will need a proper fix in sanskrit_util. After that, setup.py (of sanskrit_parser) can be corrected to remove sqlalchemy 

Opening new issue to track this.

**Comment by kmadathil** [comment]
@avinashvarna 
Can you look into this? I'm forcing a lower version of sqlalchemy to work around this issue in sanskrit_util

**Comment by codito** [comment]
I can take a look at this.

**Comment by kmadathil** [comment]
This is now more important as a security vulnerability has been flagged

**Comment by codito** [comment]
Created a fix here: https://github.com/avinashvarna/sanskrit_util/pull/1

**Comment by avinashvarna** [comment]
Thanks @codito ! Closing issue
