### ISSUE TITLE
Handle द्वित्वम् 

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#96]
dvitvam is not handled right. Specifically, the duplication caused by rules अचो रहाभ्यां द्वे , अनचि च seems to be ignored

This was discovered in the UoHD corpus testing, specifically on splits like "jawAyurdDanya eva"

**Comment by kmadathil** [comment]
I will take a look at this since @avinashvarna  seems offline.

**Comment by kmadathil** [comment]
See commit 5ce53ca for fix. Will keep this open for a while for review

**Comment by avinashvarna** [comment]
I just got back from a 2 month long international trip, and could not contribute while traveling. I will try to start looking at these issues this weekend. Thanks for continuing the development while I was away

**Comment by kmadathil** [comment]
Welcome back! Please take a look whenever you get time. I'm slowly bringing myself back up to speed after about six months off this, so your two month absence is hardly an issue :-)

**Comment by kmadathil** [comment]
Pasting the  new sandhi rule for reference 
-# द्वित्वम्
-# अचो रहाभ्यां द्वे ८.४.४६
-# अनचि च  ८.४.४७
-#  Have to split into multiple rules to handle जश्त्वम् 
-# rutvam, Visarga etc. This points to the need to 
-# have multistage rules, perhaps?
-
-[*अच्][र्, ह् ] +  [*यम् ] = {0}{1}{2} / {0}{1}{2}{2}
-[*अच्][र्, ह् ] +  [*जश् ] = {0}{1}{2} / {0}{1}{2}{2}
-[*अच्][र्, ह् ] +  घ्  = {0}{1}{2} / {0}{1}ग्घ्
-[*अच्][र्, ह् ] +  झ्   = {0}{1}{2} / {0}{1}ज्झ् 
-[*अच्][र्, ह् ] +  ढ्  = {0}{1}{2} / {0}{1}ड्ढ्
-[*अच्][र्, ह् ] +  ध्  = {0}{1}{2} / {0}{1}द्ध्
-[*अच्][र्, ह् ] +  भ्  = {0}{1}{2} / {0}{1}ब्भ्
-
-[*इच्]स् +  [*यम् ] = {0}र्{2} / {0}र्{2}{2}
-[*इच्]स् +  [*जश् ] = {0}र्{2} / {0}र्{2}{2}
-[*इच्]स् +  घ्  = {0}र्{2} / {0}र्ग्घ्
-[*इच्]स् +  झ्   = {0}र्{2} / {0}र्ज्झ् 
-[*इच्]स् +  ढ्  = {0}र्{2} / {0}र्ड्ढ्
-[*इच्]स् +  ध्  = {0}र्{2} / {0}र्द्ध्
-[*इच्]स् +  भ्  = {0}र्{2} / {0}र्ब्भ्

**Comment by avinashvarna** [comment]
These look good. What needs to be done to close this issue?

**Comment by kmadathil** [comment]
This has been merged already, I'd kept this open for your review.
